// Iex.IexEquities.Tops.IexTp.v1.56 verifier.
//
// Generated by Scaled.Historical.Verify.Cpp — do not edit.

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <map>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/classes/iex/iexequities/tops/iextp/v1.56/definitions.hpp"

namespace protocol = ::iex::iexequities::tops::iextp::v1_56;

namespace {

// Each kind of problem is printed this many times at most; every one is counted.
constexpr std::size_t shown = 10;

// What a capture came to, and what failed the rules.
struct Tally {
    std::size_t packets = 0;
    std::size_t messages = 0;
    std::size_t undecodable = 0;
    std::size_t mismatched = 0;
    std::size_t sizes = 0;
    std::size_t dispatches = 0;
    std::size_t unknown = 0;
    std::size_t trailing = 0;
    std::map<std::uint64_t, std::size_t> codes;
    std::map<std::string, std::size_t> kinds;

    // Nothing read verifies nothing, so an empty capture fails too.
    bool failed() const {
        return packets == 0 || undecodable > 0 || mismatched > 0 || sizes > 0 || dispatches > 0 || unknown > 0;
    }
};

// A message code as a number, whether its dispatch names the codes with an enum or not.
template <typename Code>
std::uint64_t code_value(Code code) {
    if constexpr (std::is_enum_v<Code>) {
        return static_cast<std::uint64_t>(static_cast<std::make_unsigned_t<std::underlying_type_t<Code>>>(code));
    } else {
        return static_cast<std::uint64_t>(static_cast<std::make_unsigned_t<Code>>(code));
    }
}

// The bytes one frame takes on the wire: its headers and the message they carry.
std::size_t frame_size(const protocol::Frame& frame) {
    return frame.encoded_size() + (frame.message() != nullptr ? frame.message()->encoded_size() : 0);
}

// Where the frames begin, given where they end: whatever precedes them is packet header.
[[maybe_unused]] std::size_t frames_begin(const std::vector<protocol::Frame>& frames, std::size_t end) {
    std::size_t total = 0;

    for (const protocol::Frame& frame : frames) { total += frame_size(frame); }

    return end >= total ? end - total : 0;
}

// The first byte two runs differ at, or the shorter length when one runs out first.
std::size_t first_difference(const std::byte* wire, std::size_t wire_length, const std::byte* encoded, std::size_t encoded_length) {
    const std::size_t common = std::min(wire_length, encoded_length);

    for (std::size_t offset = 0; offset < common; ++offset) {
        if (wire[offset] != encoded[offset]) { return offset; }
    }

    return common;
}

// Which part of a packet an offset lies in: its header, one of its frames, or past them.
std::string place(const std::vector<protocol::Frame>& frames, std::size_t begin, std::size_t offset) {
    if (offset < begin) { return "in the packet header"; }

    std::size_t start = begin;
    std::size_t index = 0;

    for (const protocol::Frame& frame : frames) {
        ++index;
        const std::size_t size = frame_size(frame);

        if (offset < start + size) {
            const std::string name = frame.message() != nullptr ? std::string(frame.message()->name()) : "no message";
            return "in frame " + std::to_string(index) + " (" + name + ")";
        }

        start += size;
    }

    return "after the last frame";
}

// The tally, one line each, then the verdict.
void summarize(const Tally& tally) {
    std::printf("== Iex.IexEquities.Tops.IexTp.v1.56 verify\n");
    std::printf("%-12s %zu\n", "packets", tally.packets);
    std::printf("%-12s %zu\n", "messages", tally.messages);
    std::printf("%-12s %zu\n", "undecodable", tally.undecodable);
    std::printf("%-12s %zu\n", "mismatched", tally.mismatched);
    std::printf("%-12s %zu\n", "size rule", tally.sizes);
    std::printf("%-12s %zu\n", "dispatch", tally.dispatches);
    std::printf("%-12s %zu\n", "unknown", tally.unknown);
    std::printf("%-12s %zu\n", "trailing", tally.trailing);

    if (!tally.codes.empty()) {
        std::printf("%-12s", "codes");
        for (const auto& [code, count] : tally.codes) { std::printf(" %llu x%zu", static_cast<unsigned long long>(code), count); }
        std::printf("\n");
    }

    for (const auto& [kind, count] : tally.kinds) {
        std::printf("  %-10s %zu\n", kind.c_str(), count);
    }

    if (tally.packets == 0) { std::printf("nothing read\n"); }

    std::printf("%s\n", tally.failed() ? "FAIL" : "PASS");
}

} // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    // One packet for the whole capture, reused the way a program reads one, so state a
    // decode fails to reset shows up here too.
    protocol::Packet decoded;
    std::vector<std::byte> encoded;
    Tally tally;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        const std::size_t number = ++tally.packets;

        try {
            decoded.decode(frame.payload, frame.payload_len);
        } catch (const protocol::DecodeError& error) {
            if (++tally.undecodable <= shown) {
                std::cerr << "packet " << number << ": does not decode: " << error.what() << '\n';
            }
            continue;
        }

        ++tally.kinds[std::string(protocol::to_string(decoded.kind()))];

        std::size_t index = 0;

        for (const protocol::Frame& held : decoded.frames()) {
            ++index;
            const protocol::Message* message = held.message();

            if (message == nullptr) { continue; }

            ++tally.messages;

            // The size rule: the length the frame's header declares against what the model reads.
            const std::size_t declared = static_cast<std::size_t>(held.message_header().message_length()) + 2;
            const std::size_t derived = frame_size(held);

            if (declared != derived && ++tally.sizes <= shown) {
                std::cerr << "packet " << number << " frame " << index << " (" << message->name() << "): declares "
                          << declared << " bytes, the model reads " << derived << '\n';
            }

            // The dispatch: a code the specification does not list, or one that selected
            // a message whose own code is another.
            if (const auto* stranger = dynamic_cast<const protocol::UnknownMessage*>(message)) {
                const std::uint64_t value = code_value(stranger->type());

                ++tally.codes[value];

                if (++tally.unknown <= shown) {
                    std::cerr << "packet " << number << " frame " << index << ": unknown message code " << value << '\n';
                }
            } else if (message->type() != held.message_header().message_type()) {
                if (++tally.dispatches <= shown) {
                    std::cerr << "packet " << number << " frame " << index << ": code " << code_value(held.message_header().message_type())
                              << " decoded as " << message->name() << ", whose code is " << code_value(message->type()) << '\n';
                }
            }
        }

        // Bytes after the last frame the model reads: a pad or a trailer the specification
        // leaves out. Kept and written back, so not a failure, but worth knowing about.
        if (!decoded.trailer().empty() && ++tally.trailing <= shown) {
            std::cerr << "packet " << number << ": " << decoded.trailer().size() << " bytes after the last frame\n";
        }

        // The round trip. Encode derives the count, every length and every code again from the
        // messages, so the bytes agree with the wire only when every rule does.
        try {
            encoded.assign(decoded.encoded_size(), std::byte{ 0 });
            const std::size_t written = decoded.encode(encoded.data(), encoded.size());
            const std::size_t offset = first_difference(frame.payload, frame.payload_len, encoded.data(), written);

            if ((written != frame.payload_len || offset < written) && ++tally.mismatched <= shown) {
                std::cerr << "packet " << number << ": encodes to " << written << " bytes against " << frame.payload_len
                          << " read, first difference at byte " << offset << ' '
                          << place(decoded.frames(), frames_begin(decoded.frames(), written - decoded.trailer().size()), offset) << '\n';
            }
        } catch (const protocol::EncodeError& error) {
            if (++tally.mismatched <= shown) {
                std::cerr << "packet " << number << ": does not encode: " << error.what() << '\n';
            }
        }
    }

    summarize(tally);

    return tally.failed() ? 1 : 0;
}
