#pragma once

#include "structs/MessageHeader.hpp"

#include "messages/SnapshotRequestMessage.hpp"
#include "messages/ErrorResponseMessage.hpp"
#include "messages/SnapshotStartMessage.hpp"
#include "messages/SnapshotDataMessage.hpp"
#include "messages/SystemEventMessage.hpp"
#include "messages/SecurityDirectoryMessage.hpp"
#include "messages/TradingStatusMessage.hpp"
#include "messages/RetailLiquidityIndicatorMessage.hpp"
#include "messages/OperationalHaltStatusMessage.hpp"
#include "messages/ShortSalePriceTestStatusMessage.hpp"
#include "messages/SecurityEventMessage.hpp"
#include "messages/AddOrderMessage.hpp"
#include "messages/OrderModifyMessage.hpp"
#include "messages/OrderDeleteMessage.hpp"
#include "messages/OrderExecutedMessage.hpp"
#include "messages/TradeMessage.hpp"
#include "messages/TradeBreakMessage.hpp"
#include "messages/ClearBookMessage.hpp"
#include "messages/SnapshotEndMessage.hpp"

#include "iterators/MessageIterator.hpp"
