// Iex.IexEquities.DeepPlus.IexTp.v1.04 message tests over the packet corpus, through the Advanced session layer.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/advanced/iex/iexequities/deepplus/iextp/v1.04/messages/session.hpp"

namespace protocol = ::iex::iexequities::deepplus::iextp::v1_04;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// The handler process_segment dispatches into: every segment is processed, every message
// counted, and the expected class counted on its own.
template <typename Expected>
struct Counter {
    std::size_t messages = 0;
    std::size_t matched = 0;

    protocol::seq_action on_transport_header(const protocol::iextp_header&, const packet::Frame&) {
        return protocol::seq_action::process;
    }

    template <typename Message>
    void on_message(const Message&, std::uint64_t, const protocol::iextp_header&) {
        ++messages;
        if constexpr (std::is_same_v<Message, Expected>) { ++matched; }
    }
};

// Walk every frame in a capture and require the expected message to be dispatched from it.
template <typename Message>
void expect(const char* name, const char* relative) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);
    Counter<Message> counter;
    std::size_t frames = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;
        protocol::process_segment(counter, frame.payload, frame.payload_len, 0, frame);
    }

    const std::size_t messages = counter.messages;
    const std::size_t matched = counter.matched;

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}

}

int main() {
    std::printf("== Iex.IexEquities.DeepPlus.IexTp.v1.04 (advanced)\n");
    expect<protocol::add_order_message>("AddOrderMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/a_AddOrder.pcap");
    expect<protocol::order_modify_message>("OrderModifyMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/M_OrderModify.pcap");
    expect<protocol::order_delete_message>("OrderDeleteMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/R_OrderDelete.pcap");
    expect<protocol::order_executed_message>("OrderExecutedMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/L_OrderExecuted.pcap");
    expect<protocol::trade_message>("TradeMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/T_Trade.pcap");
    expect<protocol::trade_break_message>("TradeBreakMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/B_TradeBreak.pcap");
    expect<protocol::security_directory_message>("SecurityDirectoryMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/D_SecurityDirectory.pcap");
    expect<protocol::security_event_message>("SecurityEventMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/E_SecurityEvent.pcap");
    expect<protocol::trading_status_message>("TradingStatusMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/H_TradingStatus.pcap");
    expect<protocol::operational_halt_status_message>("OperationalHaltStatusMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/O_OperationalHaltStatus.pcap");
    expect<protocol::short_sale_price_test_status_message>("ShortSalePriceTestStatusMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/P_ShortSalePriceTestStatus.pcap");
    expect<protocol::retail_liquidity_indicator_message>("RetailLiquidityIndicatorMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/I_RetailLiquidityIndicator.pcap");
    expect<protocol::system_event_message>("SystemEventMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.0.2/S_SystemEvent.pcap");
    return failures == 0 ? 0 : 1;
}
