// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 message tests over the packet corpus, through the Advanced session layer.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/advanced/nasdaq/nsmequities/totalview/itch/v5.0.2023/messages/session.hpp"

namespace protocol = ::nasdaq::nsmequities::totalview::itch::v5_0_2023;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// The handler process_segment dispatches into: every segment is processed, every message
// counted, and the expected class counted on its own.
template <typename Expected>
struct Counter {
    std::size_t messages = 0;
    std::size_t matched = 0;

    protocol::seq_action on_transport_header(const protocol::packet_header&, const packet::Frame&) {
        return protocol::seq_action::process;
    }

    template <typename Message>
    void on_message(const Message&, std::uint64_t, const protocol::packet_header&) {
        ++messages;
        if constexpr (std::is_same_v<Message, Expected>) { ++matched; }
    }
};

// Walk every frame in a capture and require the expected message to be dispatched from it.
template <typename Message>
void expect(const char* name, const char* relative) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);
    Counter<Message> counter;
    std::size_t frames = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;
        protocol::process_segment(counter, frame.payload, frame.payload_len, 0, frame);
    }

    const std::size_t messages = counter.messages;
    const std::size_t matched = counter.matched;

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}

}

int main() {
    std::printf("== Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 (advanced)\n");
    expect<protocol::add_order_no_mpid_attribution_message>("AddOrderNoMpidAttributionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/AddOrderNoMPID.pcap");
    expect<protocol::add_order_with_mpid_attribution_message>("AddOrderWithMpidAttributionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/AddOrderWithMPID.pcap");
    expect<protocol::cross_trade_message>("CrossTradeMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/CrossTrade.pcap");
    expect<protocol::luld_auction_collar_message>("LuldAuctionCollarMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/LULDAuctionCollar.pcap");
    expect<protocol::market_participant_position_message>("MarketParticipantPositionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/MarketParticipantPosition.pcap");
    expect<protocol::net_order_imbalance_indicator_message>("NetOrderImbalanceIndicatorMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/NetOrderImbalanceIndicator.pcap");
    expect<protocol::non_cross_trade_message>("NonCrossTradeMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/NonCrossTrade.pcap");
    expect<protocol::order_cancel_message>("OrderCancelMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderCancel.pcap");
    expect<protocol::order_delete_message>("OrderDeleteMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderDelete.pcap");
    expect<protocol::order_executed_message>("OrderExecutedMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderExecuted.pcap");
    expect<protocol::order_executed_with_price_message>("OrderExecutedWithPriceMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderExecutedWithPrice.pcap");
    expect<protocol::order_replace_message>("OrderReplaceMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderReplace.pcap");
    expect<protocol::reg_sho_short_sale_price_test_restricted_indicator_message>("RegShoShortSalePriceTestRestrictedIndicatorMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/RegSHORestriction.pcap");
    expect<protocol::stock_trading_action_message>("StockTradingActionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/StockTradingAction.pcap");
    expect<protocol::system_event_message>("SystemEventMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/SystemEvent.pcap");
    return failures == 0 ? 0 : 1;
}
