// Generated by Scaled.Historical.Extractor.Cpp — branch table for Jpx.TseEquities.MarketByOrder.Flex.v1.1.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 65ull: return "AddOrderMessage";
        case 67ull: return "OrderExecutedWithPriceMessage";
        case 68ull: return "OrderDeleteMessage";
        case 69ull: return "OrderExecutedMessage";
        case 75ull: return "ExecutionSummaryMessage";
        case 76ull: return "CommunicationControlMessage";
        case 79ull: return "TradingStatusMessage";
        case 82ull: return "ResetMessage";
        case 84ull: return "SecondsTimestampMessage";
        case 72057594037928001ull: return "LoginResultMessage";
        case 72057594037928007ull: return "EndOfMessageMessage";
        case 72057594037928018ull: return "LoginRequestMessage";
        case 72057594037928019ull: return "MessageResponseMessage";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
