// Generated by Scaled.Historical.Extractor.Cpp — per-protocol packet extractor.
// Protocol: Iex.IexEquities.DeepPlus.IexTp.v1.04

#include "program/Args.hpp"
#include "program/Runner.hpp"

#include <exception>
#include <iostream>

int main(const int argc, char** argv) {
    try {
        const auto options = program::args(argc, argv);
        program::Runner runner{ options };
        return runner.run();
    }
    catch (const std::exception& exception) {
        std::cerr << "Error: " << exception.what() << std::endl;
        return 1;
    }
    catch (...) {
        std::cerr << "Unknown exception" << std::endl;
        return 1;
    }
}
