// Iex.IexEquities.Tops.IexTp.v1.64 message tests over the packet corpus, through the Modern iterator.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/modern/iex/iexequities/tops/iextp/v1.64/definitions.hpp"

namespace protocol = ::iex::iexequities::tops::iextp::v1_64;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// Walk every frame in a capture with the iterator and require the expected message to appear in it.
template <typename Iterator, typename Matches>
void expect(const char* name, const char* relative, Matches matches) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);

    std::size_t matched = 0;
    std::size_t messages = 0;
    std::size_t frames = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;

        Iterator iterator;
        iterator.initialize(frame.payload, frame.payload_len);

        while (iterator.next()) {
            ++messages;

            if (matches(iterator)) { ++matched; }
        }
    }

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}

}

int main() {
    std::printf("== Iex.IexEquities.Tops.IexTp.v1.64 (modern)\n");
    expect<protocol::MessageIterator>("AuctionInformationMessage", "Iex/IexEquities.Tops.IexTp.v1.64/AuctionInformationMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::AuctionInformationMessage::message_type; });
    expect<protocol::MessageIterator>("OfficialPriceMessage", "Iex/IexEquities.Tops.IexTp.v1.64/OfficialPriceMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OfficialPriceMessage::message_type; });
    expect<protocol::MessageIterator>("OperationalHaltStatusMessage", "Iex/IexEquities.Tops.IexTp.v1.64/OperationalHaltStatusMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OperationalHaltStatusMessage::message_type; });
    expect<protocol::MessageIterator>("QuoteUpdateMessage", "Iex/IexEquities.Tops.IexTp.v1.64/QuoteUpdateMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::QuoteUpdateMessage::message_type; });
    expect<protocol::MessageIterator>("SecurityDirectoryMessage", "Iex/IexEquities.Tops.IexTp.v1.64/SecurityDirectoryMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::SecurityDirectoryMessage::message_type; });
    expect<protocol::MessageIterator>("ShortSalePriceTestStatusMessage", "Iex/IexEquities.Tops.IexTp.v1.64/ShortSalePriceTestStatusMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::ShortSalePriceTestStatusMessage::message_type; });
    expect<protocol::MessageIterator>("SystemEventMessage", "Iex/IexEquities.Tops.IexTp.v1.64/SystemEventMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::SystemEventMessage::message_type; });
    expect<protocol::MessageIterator>("TradeReportMessage", "Iex/IexEquities.Tops.IexTp.v1.64/TradeReportMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::TradeReportMessage::message_type; });
    expect<protocol::MessageIterator>("TradingStatusMessage", "Iex/IexEquities.Tops.IexTp.v1.64/TradingStatusMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::TradingStatusMessage::message_type; });
    return failures == 0 ? 0 : 1;
}
