// Iex.IexEquities.DeepPlus.IexTp.v1.04 message tests over the packet corpus, through the Modern iterator.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/modern/iex/iexequities/deepplus/iextp/v1.04/definitions.hpp"

namespace protocol = ::iex::iexequities::deepplus::iextp::v1_04;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// Walk every frame in a capture with the iterator and require the expected message to appear in it.
template <typename Iterator, typename Matches>
void expect(const char* name, const char* relative, Matches matches) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);

    std::size_t matched = 0;
    std::size_t messages = 0;
    std::size_t frames = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;

        Iterator iterator;
        iterator.initialize(frame.payload, frame.payload_len);

        while (iterator.next()) {
            ++messages;

            if (matches(iterator)) { ++matched; }
        }
    }

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}

}

int main() {
    std::printf("== Iex.IexEquities.DeepPlus.IexTp.v1.04 (modern)\n");
    expect<protocol::MessageIterator>("AddOrderMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/AddOrderMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::AddOrderMessage::message_type; });
    expect<protocol::MessageIterator>("OperationalHaltStatusMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/OperationalHaltStatusMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OperationalHaltStatusMessage::message_type; });
    expect<protocol::MessageIterator>("OrderDeleteMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/OrderDeleteMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderDeleteMessage::message_type; });
    expect<protocol::MessageIterator>("OrderExecutedMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/OrderExecutedMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderExecutedMessage::message_type; });
    expect<protocol::MessageIterator>("OrderModifyMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/OrderModifyMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderModifyMessage::message_type; });
    expect<protocol::MessageIterator>("RetailLiquidityIndicatorMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/RetailLiquidityIndicatorMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::RetailLiquidityIndicatorMessage::message_type; });
    expect<protocol::MessageIterator>("SecurityEventMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/SecurityEventMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::SecurityEventMessage::message_type; });
    expect<protocol::MessageIterator>("ShortSalePriceTestStatusMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/ShortSalePriceTestStatusMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::ShortSalePriceTestStatusMessage::message_type; });
    expect<protocol::MessageIterator>("SystemEventMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/SystemEventMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::SystemEventMessage::message_type; });
    expect<protocol::MessageIterator>("TradeMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/TradeMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::TradeMessage::message_type; });
    expect<protocol::MessageIterator>("TradingStatusMessage", "Iex/IexEquities.DeepPlus.IexTp.v1.04/TradingStatusMessage.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::TradingStatusMessage::message_type; });
    return failures == 0 ? 0 : 1;
}
