// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 message tests over the packet corpus, through the Modern iterator.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/modern/nasdaq/nsmequities/totalview/itch/v5.0.2023/definitions.hpp"

namespace protocol = ::nasdaq::nsmequities::totalview::itch::v5_0_2023;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// Walk every frame in a capture with the iterator and require the expected message to appear in it.
template <typename Iterator, typename Matches>
void expect(const char* name, const char* relative, Matches matches) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);

    std::size_t matched = 0;
    std::size_t messages = 0;
    std::size_t frames = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;

        Iterator iterator;
        iterator.initialize(frame.payload, frame.payload_len);

        while (iterator.next()) {
            ++messages;

            if (matches(iterator)) { ++matched; }
        }
    }

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}

}

int main() {
    std::printf("== Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 (modern)\n");
    expect<protocol::MessageIterator>("AddOrderNoMpidAttributionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/AddOrderNoMPID.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::AddOrderNoMpidAttributionMessage::message_type; });
    expect<protocol::MessageIterator>("AddOrderWithMpidAttributionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/AddOrderWithMPID.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::AddOrderWithMpidAttributionMessage::message_type; });
    expect<protocol::MessageIterator>("CrossTradeMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/CrossTrade.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::CrossTradeMessage::message_type; });
    expect<protocol::MessageIterator>("LuldAuctionCollarMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/LULDAuctionCollar.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::LuldAuctionCollarMessage::message_type; });
    expect<protocol::MessageIterator>("MarketParticipantPositionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/MarketParticipantPosition.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::MarketParticipantPositionMessage::message_type; });
    expect<protocol::MessageIterator>("NetOrderImbalanceIndicatorMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/NetOrderImbalanceIndicator.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::NetOrderImbalanceIndicatorMessage::message_type; });
    expect<protocol::MessageIterator>("NonCrossTradeMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/NonCrossTrade.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::NonCrossTradeMessage::message_type; });
    expect<protocol::MessageIterator>("OrderCancelMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderCancel.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderCancelMessage::message_type; });
    expect<protocol::MessageIterator>("OrderDeleteMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderDelete.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderDeleteMessage::message_type; });
    expect<protocol::MessageIterator>("OrderExecutedMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderExecuted.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderExecutedMessage::message_type; });
    expect<protocol::MessageIterator>("OrderExecutedWithPriceMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderExecutedWithPrice.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderExecutedWithPriceMessage::message_type; });
    expect<protocol::MessageIterator>("OrderReplaceMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderReplace.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::OrderReplaceMessage::message_type; });
    expect<protocol::MessageIterator>("RegShoShortSalePriceTestRestrictedIndicatorMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/RegSHORestriction.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::RegShoShortSalePriceTestRestrictedIndicatorMessage::message_type; });
    expect<protocol::MessageIterator>("StockTradingActionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/StockTradingAction.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::StockTradingActionMessage::message_type; });
    expect<protocol::MessageIterator>("SystemEventMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/SystemEvent.pcap", [](const protocol::MessageIterator& iterator) { return iterator.message_type == protocol::SystemEventMessage::message_type; });
    return failures == 0 ? 0 : 1;
}
