// Generated by Scaled.Historical.Extractor.Cpp — branch table for Iex.IexEquities.DeepPlus.Snap.v1.05.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 100: return "SnapshotDataMessage";
        case 101: return "ErrorResponseMessage";
        case 114: return "SnapshotRequestMessage";
        case 115: return "SnapshotStartMessage";
        case 120: return "SnapshotEndMessage";
        case 25666: return "TradeBreakMessage";
        case 25667: return "ClearBookMessage";
        case 25668: return "SecurityDirectoryMessage";
        case 25669: return "SecurityEventMessage";
        case 25672: return "TradingStatusMessage";
        case 25673: return "RetailLiquidityIndicatorMessage";
        case 25676: return "OrderExecutedMessage";
        case 25677: return "OrderModifyMessage";
        case 25679: return "OperationalHaltStatusMessage";
        case 25680: return "ShortSalePriceTestStatusMessage";
        case 25682: return "OrderDeleteMessage";
        case 25683: return "SystemEventMessage";
        case 25684: return "TradeMessage";
        case 25697: return "AddOrderMessage";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
