// Iex.IexEquities.Tops.Snap.v1.6 field dump.
//
// Generated by Scaled.Historical.Dump.Cpp — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "TcpReassembler.hpp"
#include "cpp/classes/iex/iexequities/tops/snap/v1.6/definitions.hpp"

namespace protocol = ::iex::iexequities::tops::snap::v1_6;

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    // One buffer per connection: the reassembler hands over the bytes in order, and what
    // does not yet amount to a whole frame waits here for the bytes behind it.
    std::unordered_map<packet::TcpFlowKey, std::vector<std::byte>, packet::TcpFlowKey::hash> buffers;

    std::size_t messages = 0;
    std::size_t undecodable = 0;

    packet::TcpReassembler reassembler;

    reassembler.on_data = [&](const packet::TcpFlowKey& key, const std::byte* data, std::size_t length) {
        std::vector<std::byte>& buffer = buffers[key];

        buffer.insert(buffer.end(), data, data + length);

        protocol::Stream decoded;
        std::size_t consumed = 0;

        try {
            consumed = decoded.decode(buffer.data(), buffer.size());
        } catch (const protocol::DecodeError& error) {
            ++undecodable;
            std::cerr << "undecodable stream: " << error.what() << '\n';
            buffer.clear();
            return;
        }

        for (const protocol::Frame& held : decoded.frames()) {
            if (held.message() == nullptr) { continue; }
            ++messages;
            std::cout << *held.message() << '\n';
        }

        buffer.erase(buffer.begin(), buffer.begin() + static_cast<std::ptrdiff_t>(consumed));
    };

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid() || !frame.is_tcp()) { continue; }

        reassembler.process(frame);
    }

    std::fprintf(stderr, "%zu messages\n", messages);

    for (const auto& [key, buffer] : buffers) {
        if (!buffer.empty()) {
            std::fprintf(stderr, "%zu bytes left unread on a connection\n", buffer.size());
        }
    }

    if (undecodable > 0) {
        std::fprintf(stderr, "%zu undecodable streams\n", undecodable);
    }

    return 0;
}
