// Iex.IexEquities.Tops.Snap.v1.6 field dump.
//
// Generated by Scaled.Historical.Dump.Cpp — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/modern/iex/iexequities/tops/snap/v1.6/definitions.hpp"

namespace protocol = ::iex::iexequities::tops::snap::v1_6;

namespace {

// Print one field value. The overloads keep the byte-wide types readable: without them a
// std::uint8_t prints as whatever character its value happens to be, and a char prints
// bare where a quoted one is easier to pick out of a line.
template <typename Value>
void print(const Value& value) { std::cout << value; }

void print(std::uint8_t value) { std::cout << static_cast<unsigned>(value); }
void print(std::int8_t value) { std::cout << static_cast<int>(value); }
void print(char value) { std::cout << '\'' << value << '\''; }
void print(const std::string& value) { std::cout << '"' << value << '"'; }

// Print one message's fields as name=value, comma separated.
void fields(const std::byte* message, char type) {
    switch (type) {
    case 'r': {
        const auto& value = *protocol::SnapshotRequestMessage::parse(message);
        std::cout << "Snapshot Request Message";
        std::cout << " " "Authentication Token=";
        print(value.authentication_token.get());
        std::cout << "," "Channel Id=";
        print(value.channel_id.get());
        std::cout << "," "Session Id=";
        print(value.session_id.get());
        std::cout << "," "Minimum Sequence Number=";
        print(value.minimum_sequence_number.get());
        break;
    }

    case 'e': {
        const auto& value = *protocol::ErrorResponseMessage::parse(message);
        std::cout << "Error Response Message";
        std::cout << " " "Reject Reason Code=";
        print(value.reject_reason_code.get());
        break;
    }

    case 's': {
        const auto& value = *protocol::SnapshotStartMessage::parse(message);
        std::cout << "Snapshot Start Message";
        std::cout << " " "Snapshot Length=";
        print(value.snapshot_length.get());
        break;
    }

    case 'd': {
        const auto& value = *protocol::SnapshotDataMessage::parse(message);
        std::cout << "Snapshot Data Message";
        std::cout << " " "Iex Tp Header=";
        print(value.iex_tp_header.get());
        std::cout << "," "Iex Tp Message Block Length=";
        print(value.iex_tp_message_block_length.get());
        std::cout << "," "Iex Tp Message Length=";
        print(value.iex_tp_message_length.get());
        std::cout << "," "Iex Tp Message Type=";
        print(value.iex_tp_message_type.get());
        break;
    }

    case 'x': {
        const auto& value = *protocol::SnapshotEndMessage::parse(message);
        std::cout << "Snapshot End Message";
        std::cout << " " "Snapshot Sequence Number=";
        print(value.snapshot_sequence_number.get());
        break;
    }

    default:
        std::cout << "  (unknown message type)";
        break;
    }

    std::cout << '\n';
}
}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    std::size_t count = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        protocol::MessageIterator iterator;
        iterator.initialize(frame.payload, frame.payload_len);

        while (iterator.next()) {
            ++count;
            fields(iterator.message, iterator.message_type);
        }
    }

    std::fprintf(stderr, "%zu messages\n", count);
    return 0;
}
