#pragma once

#include <cstdint>
#include <ostream>
#include <string_view>

namespace jpx::tseequities::marketbyorder::flex::v1_1 {

// When the A tag is generated by a modification order, indicates whether there is a change of
// time priority
enum class ModificationFlag : std::uint8_t {
    CancelOrderOrModificationOrderThatChangesTimePriority = 0, // Cancel Order Or Modification Order That Changes Time Priority
    ModificationOrderThatDoesNotChangeTimePriority = 1,        // Modification Order That Does Not Change Time Priority
};

// The documented name of a code, or empty for one the specification does not list
std::string_view to_string(ModificationFlag value);

// The documented name, or the raw code when there is none
std::ostream& operator<<(std::ostream& out, ModificationFlag value);

} // namespace jpx::tseequities::marketbyorder::flex::v1_1
