// Iex.IexEquities.Tops.IexTp.v1.64 message tests over the packet corpus, through the Classes Packet.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/classes/iex/iexequities/tops/iextp/v1.64/definitions.hpp"

namespace protocol = ::iex::iexequities::tops::iextp::v1_64;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// Counts the visits of one message class.
template <typename Expected>
struct Seen : protocol::Visitor {
    std::size_t matched = 0;

    void visit(const Expected&) override { ++matched; }
};

// Decode every datagram in a capture, require the expected message to be visited, and
// require every datagram to encode back to the bytes it came from.
template <typename Message>
void expect(const char* name, const char* relative) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);
    Seen<Message> seen;
    std::vector<std::byte> buffer;

    std::size_t frames = 0;
    std::size_t messages = 0;
    std::size_t undecodable = 0;
    std::size_t mismatched = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;
        protocol::Packet decoded;

        try {
            decoded.decode(frame.payload, frame.payload_len);
        } catch (const protocol::DecodeError& error) {
            ++undecodable;
            std::printf("  undecodable datagram: %s\n", error.what());
            continue;
        }

        messages += decoded.frames().size();
        decoded.accept(seen);

        buffer.assign(decoded.encoded_size(), std::byte{ 0 });
        const std::size_t written = decoded.encode(buffer.data(), buffer.size());

        if (written != frame.payload_len || std::memcmp(buffer.data(), frame.payload, written) != 0) {
            ++mismatched;
        }
    }

    const std::size_t matched = seen.matched;

    if (undecodable > 0) {
        std::printf("FAIL %s: %zu datagrams did not decode\n", name, undecodable);
        ++failures;
        return;
    }

    if (mismatched > 0) {
        std::printf("FAIL %s: %zu datagrams did not encode back to their bytes\n", name, mismatched);
        ++failures;
        return;
    }

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}

}

int main() {
    std::printf("== Iex.IexEquities.Tops.IexTp.v1.64 (classes)\n");
    expect<protocol::QuoteUpdateMessage>("QuoteUpdateMessage", "Iex/IexEquities.Tops.IexTp.v1.64/QuoteUpdateMessage.pcap");
    return failures == 0 ? 0 : 1;
}
