// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 message tests over the packet corpus, through the Classes Packet.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/classes/nasdaq/nsmequities/totalview/itch/v5.0.2023/definitions.hpp"

namespace protocol = ::nasdaq::nsmequities::totalview::itch::v5_0_2023;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// Counts the visits of one message class, through the visitor its own dispatch is seen by.
template <typename Visitor, typename Expected>
struct Seen : Visitor {
    std::size_t matched = 0;

    void visit(const Expected&) override { ++matched; }
};

// Decode every datagram in a capture, require the expected message to be visited, and
// require every datagram to encode back to the bytes it came from.
template <typename Packet, typename Visitor, typename Message>
void expect(const char* name, const char* relative) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);
    Seen<Visitor, Message> seen;
    std::vector<std::byte> buffer;

    std::size_t frames = 0;
    std::size_t messages = 0;
    std::size_t undecodable = 0;
    std::size_t mismatched = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;
        Packet decoded;

        try {
            decoded.decode(frame.payload, frame.payload_len);
        } catch (const protocol::DecodeError& error) {
            ++undecodable;
            std::printf("  undecodable datagram: %s\n", error.what());
            continue;
        }

        messages += decoded.frames().size();
        decoded.accept(seen);

        buffer.assign(decoded.encoded_size(), std::byte{ 0 });
        const std::size_t written = decoded.encode(buffer.data(), buffer.size());

        if (written != frame.payload_len || std::memcmp(buffer.data(), frame.payload, written) != 0) {
            ++mismatched;
        }
    }

    const std::size_t matched = seen.matched;

    if (undecodable > 0) {
        std::printf("FAIL %s: %zu datagrams did not decode\n", name, undecodable);
        ++failures;
        return;
    }

    if (mismatched > 0) {
        std::printf("FAIL %s: %zu datagrams did not encode back to their bytes\n", name, mismatched);
        ++failures;
        return;
    }

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}

}

int main() {
    std::printf("== Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 (classes)\n");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadAddOrderNoMpidAttributionMessage>("AddOrderNoMpidAttributionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/AddOrderNoMPID.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadAddOrderWithMpidAttributionMessage>("AddOrderWithMpidAttributionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/AddOrderWithMPID.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadCrossTradeMessage>("CrossTradeMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/CrossTrade.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadLuldAuctionCollarMessage>("LuldAuctionCollarMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/LULDAuctionCollar.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadMarketParticipantPositionMessage>("MarketParticipantPositionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/MarketParticipantPosition.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadNetOrderImbalanceIndicatorMessage>("NetOrderImbalanceIndicatorMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/NetOrderImbalanceIndicator.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadNonCrossTradeMessage>("NonCrossTradeMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/NonCrossTrade.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadOrderCancelMessage>("OrderCancelMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderCancel.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadOrderDeleteMessage>("OrderDeleteMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderDelete.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadOrderExecutedMessage>("OrderExecutedMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderExecuted.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadOrderExecutedWithPriceMessage>("OrderExecutedWithPriceMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderExecutedWithPrice.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadOrderReplaceMessage>("OrderReplaceMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/OrderReplace.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadRegShoShortSalePriceTestRestrictedIndicatorMessage>("RegShoShortSalePriceTestRestrictedIndicatorMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/RegSHORestriction.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadStockTradingActionMessage>("StockTradingActionMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/StockTradingAction.pcap");
    expect<protocol::Packet, protocol::PacketMessageVisitor, protocol::PayloadSystemEventMessage>("SystemEventMessage", "Nasdaq/NsmEquities.TotalView.Itch.v5.0.2023/SystemEvent.pcap");
    return failures == 0 ? 0 : 1;
}
