// Generated by Scaled.Historical.Extractor.Cpp — branch table for Iex.IexEquities.DeepPlus.Snap.v1.06.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 100ull: return "SnapshotDataMessage";
        case 101ull: return "ErrorResponseMessage";
        case 114ull: return "SnapshotRequestMessage";
        case 115ull: return "SnapshotStartMessage";
        case 120ull: return "SnapshotEndMessage";
        case 429496729666ull: return "TradeBreakMessage";
        case 429496729667ull: return "ClearBookMessage";
        case 429496729668ull: return "SecurityDirectoryMessage";
        case 429496729669ull: return "SecurityEventMessage";
        case 429496729672ull: return "TradingStatusMessage";
        case 429496729673ull: return "RetailLiquidityIndicatorMessage";
        case 429496729676ull: return "OrderExecutedMessage";
        case 429496729677ull: return "OrderModifyMessage";
        case 429496729679ull: return "OperationalHaltStatusMessage";
        case 429496729680ull: return "ShortSalePriceTestStatusMessage";
        case 429496729682ull: return "OrderDeleteMessage";
        case 429496729683ull: return "SystemEventMessage";
        case 429496729684ull: return "TradeMessage";
        case 429496729697ull: return "AddOrderMessage";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
