// Generated by Scaled.Historical.Extractor.Cpp — branch table for Iex.IexEquities.Tops.Snap.v1.6.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 100: return "SnapshotDataMessage";
        case 101: return "ErrorResponseMessage";
        case 114: return "SnapshotRequestMessage";
        case 115: return "SnapshotStartMessage";
        case 120: return "SnapshotEndMessage";
        case 25665: return "AuctionInformationMessage";
        case 25666: return "TradeBreakMessage";
        case 25668: return "SecurityDirectoryMessage";
        case 25672: return "TradingStatusMessage";
        case 25673: return "RetailLiquidityIndicatorMessage";
        case 25679: return "OperationalHaltStatusMessage";
        case 25680: return "ShortSalePriceTestStatusMessage";
        case 25681: return "QuoteUpdateMessage";
        case 25683: return "SystemEventMessage";
        case 25684: return "TradeReportMessage";
        case 25688: return "OfficialPriceMessage";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
