// Iex.IexEquities.DeepPlus.Snap.v1.06 field dump.
//
// Generated by Scaled.Historical.Dump.Cpp — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "TcpReassembler.hpp"
#include "cpp/classes/iex/iexequities/deepplus/snap/v1.06/definitions.hpp"

namespace protocol = ::iex::iexequities::deepplus::snap::v1_06;

namespace {

// Every message a read frames, printed through the message's own print. A tree's frame class
// is its own, so the frames are taken as they come rather than by naming their type.
constexpr auto framed = [](const auto& read) {
    std::size_t messages = 0;

    for (const auto& held : read.frames()) {
        if (held.message() == nullptr) { continue; }

        ++messages;
        std::cout << *held.message() << '\n';
    }

    return messages;
};

// A connection's bytes: whatever whole frames they hold are read out, and what does not yet
// amount to a frame waits in the buffer for the bytes behind it.
template <typename Read, typename Printer>
std::size_t reassembled(std::vector<std::byte>& buffer, std::size_t& undecodable, Printer printer) {
    Read decoded;
    std::size_t consumed = 0;

    try {
        consumed = decoded.decode(buffer.data(), buffer.size());
    } catch (const protocol::DecodeError& error) {
        ++undecodable;
        std::cerr << "undecodable stream: " << error.what() << '\n';
        buffer.clear();
        return 0;
    }

    const std::size_t messages = printer(decoded);

    buffer.erase(buffer.begin(), buffer.begin() + static_cast<std::ptrdiff_t>(consumed));

    return messages;
}

}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    std::size_t messages = 0;
    std::size_t undecodable = 0;

    // One buffer per connection: the reassembler hands over the bytes in order, and what
    // does not yet amount to a whole frame waits here for the bytes behind it.
    std::unordered_map<packet::TcpFlowKey, std::vector<std::byte>, packet::TcpFlowKey::hash> buffers;

    packet::TcpReassembler reassembler;

    reassembler.on_data = [&](const packet::TcpFlowKey& key, const std::byte* data, std::size_t length) {
        std::vector<std::byte>& buffer = buffers[key];

        buffer.insert(buffer.end(), data, data + length);

        messages += reassembled<protocol::Stream>(buffer, undecodable, framed);
    };

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        if (frame.is_tcp()) {
            reassembler.process(frame);
        }
    }

    std::fprintf(stderr, "%zu messages\n", messages);

    for (const auto& [key, buffer] : buffers) {
        if (!buffer.empty()) {
            std::fprintf(stderr, "%zu bytes left unread on a connection\n", buffer.size());
        }
    }

    if (undecodable > 0) {
        std::fprintf(stderr, "%zu reads did not decode\n", undecodable);
    }

    return 0;
}
