#pragma once

#include <cstddef>
#include <cstdint>
#include <ostream>
#include <string>

namespace jpx::tseequities::marketbyorder::flex::v1_1 {

// Jpx Flex 26 byte packet header
class PacketHeader {
  public:
    // Bytes of this struct on the wire
    static constexpr std::size_t wire_size = 26;

    PacketHeader() = default;
    PacketHeader(std::uint8_t multicast_group_number, std::uint8_t number_of_system_reboots, std::uint32_t sequence_number, const std::string& issue_code, std::uint32_t update_number, std::uint8_t packet_number, std::uint8_t total_number_of_packets, std::uint8_t utility_flag, std::uint8_t message_count);

    // Multicast Group Number: Multicast Group Number for the request target
    std::uint8_t multicast_group_number() const;
    void set_multicast_group_number(std::uint8_t value);

    // Number Of System Reboots: For retransmission set to the number of times the system has
    // been rebooted; for snapshot set to 0
    std::uint8_t number_of_system_reboots() const;
    void set_number_of_system_reboots(std::uint8_t value);

    // Sequence Number: For retransmission set to the first sequence number for the request;
    // for snapshot set to 0
    std::uint32_t sequence_number() const;
    void set_sequence_number(std::uint32_t value);

    // Issue Code: Securities Identification Code left aligned with trailing spaces
    const std::string& issue_code() const;
    std::string& issue_code();
    void set_issue_code(const std::string& value);

    // Update Number: Per issue update number assigned from 1 each business day
    std::uint32_t update_number() const;
    void set_update_number(std::uint32_t value);

    // Packet Number: Packet number within a multi packet split set always 0 in arrowhead4 0
    std::uint8_t packet_number() const;
    void set_packet_number(std::uint8_t value);

    // Total Number Of Packets: Total packet count within a multi packet split set always 0 in
    // arrowhead4 0
    std::uint8_t total_number_of_packets() const;
    void set_total_number_of_packets(std::uint8_t value);

    // Utility Flag: Indicates whether another packet follows that was generated by the same
    // transaction
    std::uint8_t utility_flag() const;
    void set_utility_flag(std::uint8_t value);

    // Message Count: Number of tags in the packet
    std::uint8_t message_count() const;
    void set_message_count(std::uint8_t value);

    // Read this from the bytes at data, and return how many were consumed; throws DecodeError when too few
    std::size_t decode(const std::byte* data, std::size_t length);
    // Write this to the bytes at data, and return how many were written; throws EncodeError when too few
    std::size_t encode(std::byte* data, std::size_t capacity) const;
    // How many bytes encode would write
    std::size_t encoded_size() const;
    void print(std::ostream& out) const;

    bool operator==(const PacketHeader& other) const;
    bool operator!=(const PacketHeader& other) const;

  private:
    std::uint8_t multicast_group_number_{};
    std::uint8_t number_of_system_reboots_{};
    std::uint32_t sequence_number_{};
    std::string issue_code_{};
    std::uint32_t update_number_{};
    std::uint8_t packet_number_{};
    std::uint8_t total_number_of_packets_{};
    std::uint8_t utility_flag_{};
    std::uint8_t message_count_{};
};

std::ostream& operator<<(std::ostream& out, const PacketHeader& value);

} // namespace jpx::tseequities::marketbyorder::flex::v1_1
