// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 field dump.
//
// Generated by Scaled.Historical.Dump.Cpp — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "TcpReassembler.hpp"
#include "cpp/classes/nasdaq/nsmequities/totalview/itch/v5.0.2023/definitions.hpp"

namespace protocol = ::nasdaq::nsmequities::totalview::itch::v5_0_2023;

namespace {

// Every message a read frames, printed through the message's own print. A tree's frame class
// is its own, so the frames are taken as they come rather than by naming their type.
constexpr auto framed = [](const auto& read) {
    std::size_t messages = 0;

    for (const auto& held : read.frames()) {
        if (held.message() == nullptr) { continue; }

        ++messages;
        std::cout << *held.message() << '\n';
    }

    return messages;
};

// A frame that arrives whole is a whole packet: what it does not hold belongs to no other frame.
template <typename Read, typename Printer>
std::size_t whole(const packet::Frame& frame, std::size_t& undecodable, Printer printer) {
    Read decoded;

    try {
        decoded.decode(frame.payload, frame.payload_len);
    } catch (const protocol::DecodeError& error) {
        ++undecodable;
        std::cerr << "undecodable frame: " << error.what() << '\n';
        return 0;
    }

    return printer(decoded);
}

// A connection's bytes: whatever whole frames they hold are read out, and what does not yet
// amount to a frame waits in the buffer for the bytes behind it.
template <typename Read, typename Printer>
std::size_t reassembled(std::vector<std::byte>& buffer, std::size_t& undecodable, Printer printer) {
    Read decoded;
    std::size_t consumed = 0;

    try {
        consumed = decoded.decode(buffer.data(), buffer.size());
    } catch (const protocol::DecodeError& error) {
        ++undecodable;
        std::cerr << "undecodable stream: " << error.what() << '\n';
        buffer.clear();
        return 0;
    }

    const std::size_t messages = printer(decoded);

    buffer.erase(buffer.begin(), buffer.begin() + static_cast<std::ptrdiff_t>(consumed));

    return messages;
}

// Which endpoint of a connection was dialled: the server's. Either half of the handshake says
// so — a SYN carrying no ACK is addressed to the side that was dialled, and the SYN that
// answers it comes from that side. A connection whose handshake the capture missed says
// neither, and its bytes are counted as a side unknown and read as the client's.
struct Sides {
    static constexpr std::uint8_t SYN = 0x02;
    static constexpr std::uint8_t ACK = 0x10;

    struct Endpoint {
        std::uint32_t ip = 0;     // network byte order
        std::uint16_t port = 0;   // host byte order

        bool operator==(const Endpoint& other) const noexcept = default;

        struct hash {
            std::size_t operator()(const Endpoint& endpoint) const noexcept {
                return std::hash<std::uint64_t>{}((std::uint64_t(endpoint.ip) << 16) | endpoint.port);
            }
        };
    };

    std::unordered_set<Endpoint, Endpoint::hash> dialled;
    std::size_t unknown = 0;

    // Every frame is offered: only the handshake's two frames say anything.
    void saw(const packet::Frame& frame) {
        if ((frame.tcp_flags & SYN) == 0) { return; }

        if ((frame.tcp_flags & ACK) == 0) {
            dialled.insert(Endpoint{ frame.dst_ip, frame.dst_port });   // the side dialled
            return;
        }

        dialled.insert(Endpoint{ frame.src_ip, frame.src_port });       // the side that answered
    }

    // Whether these bytes came from the server. A connection nothing was learned about is
    // counted once per run and read as the client's.
    bool from_server(std::uint32_t ip, std::uint16_t port, std::uint32_t other_ip, std::uint16_t other_port) {
        if (dialled.contains(Endpoint{ ip, port })) { return true; }
        if (dialled.contains(Endpoint{ other_ip, other_port })) { return false; }

        ++unknown;

        return false;
    }
};

}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    std::size_t messages = 0;
    std::size_t undecodable = 0;

    // Which endpoint of each connection was dialled, learned from the handshake as it goes by.
    Sides sides;

    // One buffer per connection: the reassembler hands over the bytes in order, and what
    // does not yet amount to a whole frame waits here for the bytes behind it.
    std::unordered_map<packet::TcpFlowKey, std::vector<std::byte>, packet::TcpFlowKey::hash> buffers;

    packet::TcpReassembler reassembler;

    reassembler.on_data = [&](const packet::TcpFlowKey& key, const std::byte* data, std::size_t length) {
        std::vector<std::byte>& buffer = buffers[key];

        buffer.insert(buffer.end(), data, data + length);

        if (sides.from_server(key.src_ip, key.src_port, key.dst_ip, key.dst_port)) {
            messages += reassembled<protocol::ServerPacket>(buffer, undecodable, framed);
            return;
        }

        messages += reassembled<protocol::ClientPacket>(buffer, undecodable, framed);
    };

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        if (frame.is_udp()) {
            messages += whole<protocol::Packet>(frame, undecodable, framed);
            continue;
        }

        if (frame.is_tcp()) {
            sides.saw(frame);
            reassembler.process(frame);
        }
    }

    std::fprintf(stderr, "%zu messages\n", messages);

    for (const auto& [key, buffer] : buffers) {
        if (!buffer.empty()) {
            std::fprintf(stderr, "%zu bytes left unread on a connection\n", buffer.size());
        }
    }

    if (sides.unknown > 0) {
        std::fprintf(stderr, "%zu reads on connections whose handshake the capture missed, read as the client's\n", sides.unknown);
    }

    if (undecodable > 0) {
        std::fprintf(stderr, "%zu reads did not decode\n", undecodable);
    }

    return 0;
}
