// Iex.IexEquities.Tops.IexTp.v1.56 field dump.
//
// Generated by Scaled.Historical.Dump.Cpp — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/modern/iex/iexequities/tops/iextp/v1.56/definitions.hpp"

namespace protocol = ::iex::iexequities::tops::iextp::v1_56;

namespace {

// Print one field value. The overloads keep the byte-wide types readable: without them a
// std::uint8_t prints as whatever character its value happens to be, and a char prints
// bare where a quoted one is easier to pick out of a line.
template <typename Value>
void print(const Value& value) { std::cout << value; }

void print(std::uint8_t value) { std::cout << static_cast<unsigned>(value); }
void print(std::int8_t value) { std::cout << static_cast<int>(value); }
void print(char value) { std::cout << '\'' << value << '\''; }
void print(const std::string& value) { std::cout << '"' << value << '"'; }

// Print one message's fields as name=value, comma separated.
void fields(const std::byte* message, char type) {
    switch (type) {
    case 'S': {
        const auto& value = *protocol::SystemEventMessage::parse(message);
        std::cout << "System Event Message";
        std::cout << " " "System Event=";
        print(value.system_event.get());
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        break;
    }

    case 'D': {
        const auto& value = *protocol::SecurityDirectoryMessage::parse(message);
        std::cout << "Security Directory Message";
        std::cout << " " "Security Directory Flags.Etp=" << value.security_directory_flags.Etp();
        std::cout << "," "Security Directory Flags.WhenIssued=" << value.security_directory_flags.WhenIssued();
        std::cout << "," "Security Directory Flags.TestSecurity=" << value.security_directory_flags.TestSecurity();
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Round Lot Size=";
        print(value.round_lot_size.get());
        std::cout << "," "Adjusted Poc Price=";
        print(value.adjusted_poc_price.get());
        std::cout << "," "Luld Tier=";
        print(value.luld_tier.get());
        break;
    }

    case 'H': {
        const auto& value = *protocol::TradingStatusMessage::parse(message);
        std::cout << "Trading Status Message";
        std::cout << " " "Trading Status=";
        print(value.trading_status.get());
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Reason=";
        print(value.reason.get());
        break;
    }

    case 'O': {
        const auto& value = *protocol::OperationalHaltStatusMessage::parse(message);
        std::cout << "Operational Halt Status Message";
        std::cout << " " "Operational Halt Status=";
        print(value.operational_halt_status.get());
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        break;
    }

    case 'P': {
        const auto& value = *protocol::ShortSalePriceTestStatusMessage::parse(message);
        std::cout << "Short Sale Price Test Status Message";
        std::cout << " " "Short Sale Price Test Status=";
        print(value.short_sale_price_test_status.get());
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Detail=";
        print(value.detail.get());
        break;
    }

    case 'E': {
        const auto& value = *protocol::SecurityEventMessage::parse(message);
        std::cout << "Security Event Message";
        std::cout << " " "Security Event=";
        print(value.security_event.get());
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        break;
    }

    case 'Q': {
        const auto& value = *protocol::QuoteUpdateMessage::parse(message);
        std::cout << "Quote Update Message";
        std::cout << " " "Quote Update Flags.MarketSession=" << value.quote_update_flags.MarketSession();
        std::cout << "," "Quote Update Flags.SymbolAvailability=" << value.quote_update_flags.SymbolAvailability();
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Bid Size=";
        print(value.bid_size.get());
        std::cout << "," "Bid Price=";
        print(value.bid_price.get());
        std::cout << "," "Ask Price=";
        print(value.ask_price.get());
        std::cout << "," "Ask Size=";
        print(value.ask_size.get());
        break;
    }

    case 'T': {
        const auto& value = *protocol::TradeReportMessage::parse(message);
        std::cout << "Trade Report Message";
        std::cout << " " "Sale Condition Flags.TradeThroughExempt=" << value.sale_condition_flags.TradeThroughExempt();
        std::cout << "," "Sale Condition Flags.OddLot=" << value.sale_condition_flags.OddLot();
        std::cout << "," "Sale Condition Flags.ExtendedHours=" << value.sale_condition_flags.ExtendedHours();
        std::cout << "," "Sale Condition Flags.IntermarketSweep=" << value.sale_condition_flags.IntermarketSweep();
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Size=";
        print(value.size.get());
        std::cout << "," "Price=";
        print(value.price.get());
        std::cout << "," "Trade Id=";
        print(value.trade_id.get());
        break;
    }

    case 'X': {
        const auto& value = *protocol::OfficialPriceMessage::parse(message);
        std::cout << "Official Price Message";
        std::cout << " " "Price Type=";
        print(value.price_type.get());
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Official Price=";
        print(value.official_price.get());
        break;
    }

    case 'B': {
        const auto& value = *protocol::TradeBreakMessage::parse(message);
        std::cout << "Trade Break Message";
        std::cout << " " "Sale Condition Flags.TradeThroughExempt=" << value.sale_condition_flags.TradeThroughExempt();
        std::cout << "," "Sale Condition Flags.OddLot=" << value.sale_condition_flags.OddLot();
        std::cout << "," "Sale Condition Flags.ExtendedHours=" << value.sale_condition_flags.ExtendedHours();
        std::cout << "," "Sale Condition Flags.IntermarketSweep=" << value.sale_condition_flags.IntermarketSweep();
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Size=";
        print(value.size.get());
        std::cout << "," "Price=";
        print(value.price.get());
        std::cout << "," "Trade Id=";
        print(value.trade_id.get());
        break;
    }

    case 'A': {
        const auto& value = *protocol::AuctionInformationMessage::parse(message);
        std::cout << "Auction Information Message";
        std::cout << " " "Auction Type=";
        print(value.auction_type.get());
        std::cout << "," "Timestamp=";
        print(value.timestamp.get());
        std::cout << "," "Symbol=";
        print(value.symbol.get());
        std::cout << "," "Paired Shares=";
        print(value.paired_shares.get());
        std::cout << "," "Reference Price=";
        print(value.reference_price.get());
        std::cout << "," "Indicative Clearing Price=";
        print(value.indicative_clearing_price.get());
        std::cout << "," "Imbalance Shares=";
        print(value.imbalance_shares.get());
        std::cout << "," "Imbalance Side=";
        print(value.imbalance_side.get());
        std::cout << "," "Extension Number=";
        print(value.extension_number.get());
        std::cout << "," "Scheduled Auction Time=";
        print(value.scheduled_auction_time.get());
        std::cout << "," "Auction Book Clearing Price=";
        print(value.auction_book_clearing_price.get());
        std::cout << "," "Collar Reference Price=";
        print(value.collar_reference_price.get());
        std::cout << "," "Lower Auction Collar=";
        print(value.lower_auction_collar.get());
        std::cout << "," "Upper Auction Collar=";
        print(value.upper_auction_collar.get());
        break;
    }

    default:
        std::cout << "  (unknown message type)";
        break;
    }

    std::cout << '\n';
}
}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    std::size_t count = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        protocol::MessageIterator iterator;
        iterator.initialize(frame.payload, frame.payload_len);

        while (iterator.next()) {
            ++count;
            fields(iterator.message, iterator.message_type);
        }
    }

    std::fprintf(stderr, "%zu messages\n", count);
    return 0;
}
