// Generated by Scaled.Historical.Extractor.Cpp — branch table for Iex.IexEquities.Deep.IexTp.v1.08.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 0: return "Heartbeat";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
