// Generated by Scaled.Historical.Extractor.Cpp — branch table for B3.B3Derivatives.BinaryUmdf.Sbe.v1.6.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 1ull: return "SequenceResetMessage";
        case 2ull: return "SequenceMessage";
        case 3ull: return "SecurityStatus3Message";
        case 4ull: return "DeprecatedSecurityDefinitionMessage";
        case 5ull: return "News5Message";
        case 9ull: return "EmptyBookMessage";
        case 10ull: return "SecurityGroupPhase10Message";
        case 11ull: return "ChannelReset11Message";
        case 15ull: return "OpeningPrice15Message";
        case 16ull: return "TheoreticalOpeningPrice16Message";
        case 17ull: return "ClosingPrice17Message";
        case 19ull: return "AuctionImbalance19Message";
        case 20ull: return "PriceBand20Message";
        case 21ull: return "QuantityBand21Message";
        case 24ull: return "HighPrice24Message";
        case 25ull: return "LowPrice25Message";
        case 27ull: return "LastTradePrice27Message";
        case 30ull: return "SnapshotFullRefreshHeader30Message";
        case 50ull: return "OrderMbO50Message";
        case 51ull: return "DeleteOrderMbO51Message";
        case 52ull: return "MassDeleteOrdersMbO52Message";
        case 53ull: return "Trade53Message";
        case 54ull: return "ForwardTrade54Message";
        case 55ull: return "ExecutionSummary55Message";
        case 56ull: return "ExecutionStatistics56Message";
        case 57ull: return "TradeBust57Message";
        case 71ull: return "SnapshotFullRefreshOrdersMbO71Message";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
