// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 verifier.
//
// Generated by Scaled.Historical.Verify.Cpp — do not edit.

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <map>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "TcpReassembler.hpp"
#include "cpp/classes/nasdaq/nsmequities/totalview/itch/v5.0.2023/definitions.hpp"

namespace protocol = ::nasdaq::nsmequities::totalview::itch::v5_0_2023;

namespace {

// Each kind of problem is printed this many times at most; every one is counted.
constexpr std::size_t shown = 10;

// What a capture came to, and what failed the rules.
struct Tally {
    std::size_t packets = 0;
    std::size_t messages = 0;
    std::size_t undecodable = 0;
    std::size_t mismatched = 0;
    std::size_t sizes = 0;
    std::size_t dispatches = 0;
    std::size_t unknown = 0;
    std::size_t trailing = 0;
    std::map<std::uint64_t, std::size_t> codes;
    std::map<std::string, std::size_t> kinds;

    // Nothing read verifies nothing, so an empty capture fails too.
    bool failed() const {
        return packets == 0 || undecodable > 0 || mismatched > 0 || sizes > 0 || dispatches > 0 || unknown > 0;
    }
};

// A message code as a number, whether its dispatch names the codes with an enum or not.
template <typename Code>
std::uint64_t code_value(Code code) {
    if constexpr (std::is_enum_v<Code>) {
        return static_cast<std::uint64_t>(static_cast<std::make_unsigned_t<std::underlying_type_t<Code>>>(code));
    } else {
        return static_cast<std::uint64_t>(static_cast<std::make_unsigned_t<Code>>(code));
    }
}

// The bytes one frame takes on the wire: its headers and the message they carry. A tree's frame
// class is its own, so every helper here takes whichever frame class it is handed.
template <typename Frame>
std::size_t frame_size(const Frame& frame) {
    return frame.encoded_size() + (frame.message() != nullptr ? frame.message()->encoded_size() : 0);
}

// Where the frames begin, given where they end: whatever precedes them is packet header.
template <typename Frame>
std::size_t frames_begin(const std::vector<Frame>& frames, std::size_t end) {
    std::size_t total = 0;

    for (const Frame& frame : frames) { total += frame_size(frame); }

    return end >= total ? end - total : 0;
}

// The first byte two runs differ at, or the shorter length when one runs out first.
std::size_t first_difference(const std::byte* wire, std::size_t wire_length, const std::byte* encoded, std::size_t encoded_length) {
    const std::size_t common = std::min(wire_length, encoded_length);

    for (std::size_t offset = 0; offset < common; ++offset) {
        if (wire[offset] != encoded[offset]) { return offset; }
    }

    return common;
}

// Which part of a read an offset lies in: its packet header, one of its frames, or past them.
template <typename Frame>
std::string place(const std::vector<Frame>& frames, std::size_t begin, std::size_t offset) {
    if (offset < begin) { return "in the packet header"; }

    std::size_t start = begin;
    std::size_t index = 0;

    for (const Frame& frame : frames) {
        ++index;
        const std::size_t size = frame_size(frame);

        if (offset < start + size) {
            const std::string name = frame.message() != nullptr ? std::string(frame.message()->name()) : "no message";
            return "in frame " + std::to_string(index) + " (" + name + ")";
        }

        start += size;
    }

    return "after the last frame";
}

// The tally, one line each, then the verdict.
void summarize(const Tally& tally) {
    std::printf("== Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023 verify\n");
    std::printf("%-12s %zu\n", "reads", tally.packets);
    std::printf("%-12s %zu\n", "messages", tally.messages);
    std::printf("%-12s %zu\n", "undecodable", tally.undecodable);
    std::printf("%-12s %zu\n", "mismatched", tally.mismatched);
    std::printf("%-12s %zu\n", "size rule", tally.sizes);
    std::printf("%-12s %zu\n", "dispatch", tally.dispatches);
    std::printf("%-12s %zu\n", "unknown", tally.unknown);
    std::printf("%-12s %zu\n", "trailing", tally.trailing);

    if (!tally.codes.empty()) {
        std::printf("%-12s", "codes");
        for (const auto& [code, count] : tally.codes) { std::printf(" %llu x%zu", static_cast<unsigned long long>(code), count); }
        std::printf("\n");
    }

    for (const auto& [kind, count] : tally.kinds) {
        std::printf("  %-10s %zu\n", kind.c_str(), count);
    }

    if (tally.packets == 0) { std::printf("nothing read\n"); }

    std::printf("%s\n", tally.failed() ? "FAIL" : "PASS");
}


// Which endpoint of a connection was dialled: the server's. Either half of the handshake says
// so — a SYN carrying no ACK is addressed to the side that was dialled, and the SYN that
// answers it comes from that side. A connection whose handshake the capture missed says
// neither, and its bytes are counted as a side unknown and read as the client's.
struct Sides {
    static constexpr std::uint8_t SYN = 0x02;
    static constexpr std::uint8_t ACK = 0x10;

    struct Endpoint {
        std::uint32_t ip = 0;     // network byte order
        std::uint16_t port = 0;   // host byte order

        bool operator==(const Endpoint& other) const noexcept = default;

        struct hash {
            std::size_t operator()(const Endpoint& endpoint) const noexcept {
                return std::hash<std::uint64_t>{}((std::uint64_t(endpoint.ip) << 16) | endpoint.port);
            }
        };
    };

    std::unordered_set<Endpoint, Endpoint::hash> dialled;
    std::size_t unknown = 0;

    // Every frame is offered: only the handshake's two frames say anything.
    void saw(const packet::Frame& frame) {
        if ((frame.tcp_flags & SYN) == 0) { return; }

        if ((frame.tcp_flags & ACK) == 0) {
            dialled.insert(Endpoint{ frame.dst_ip, frame.dst_port });   // the side dialled
            return;
        }

        dialled.insert(Endpoint{ frame.src_ip, frame.src_port });       // the side that answered
    }

    // Whether these bytes came from the server. A connection nothing was learned about is
    // counted once per run and read as the client's.
    bool from_server(std::uint32_t ip, std::uint16_t port, std::uint32_t other_ip, std::uint16_t other_port) {
        if (dialled.contains(Endpoint{ ip, port })) { return true; }
        if (dialled.contains(Endpoint{ other_ip, other_port })) { return false; }

        ++unknown;

        return false;
    }
};
// Packet: a frame of its transport is a whole packet of its own.
void read_packet(protocol::Packet& decoded, const packet::Frame& frame, Tally& tally, std::vector<std::byte>& encoded) {
    const std::size_t number = ++tally.packets;

    try {
        decoded.decode(frame.payload, frame.payload_len);
    } catch (const protocol::DecodeError& error) {
        if (++tally.undecodable <= shown) {
            std::cerr << "read " << number << ": does not decode: " << error.what() << '\n';
        }
        return;
    }

    ++tally.kinds[std::string(protocol::to_string(decoded.kind()))];

    std::size_t index = 0;

    for (const auto& held : decoded.frames()) {
        ++index;
        const protocol::PacketMessage* message = held.message();

        if (message == nullptr) { continue; }

        ++tally.messages;

        // The size rule: the length the frame's header declares against what the model reads.
        const std::size_t declared = static_cast<std::size_t>(held.message_header().message_length()) + 2;
        const std::size_t derived = frame_size(held);

        if (declared != derived && ++tally.sizes <= shown) {
            std::cerr << "read " << number << " frame " << index << " (" << message->name() << "): declares "
                      << declared << " bytes, the model reads " << derived << '\n';
        }

        // The dispatch: a code the specification does not list, or one that selected
        // a message whose own code is another.
        if (const auto* stranger = dynamic_cast<const protocol::UnknownPacketMessage*>(message)) {
            const std::uint64_t value = code_value(stranger->type());

            ++tally.codes[value];

            if (++tally.unknown <= shown) {
                std::cerr << "read " << number << " frame " << index << ": unknown message code " << value << '\n';
            }
        } else if (message->type() != held.message_header().message_type()) {
            if (++tally.dispatches <= shown) {
                std::cerr << "read " << number << " frame " << index << ": code " << code_value(held.message_header().message_type())
                          << " decoded as " << message->name() << ", whose code is " << code_value(message->type()) << '\n';
            }
        }
    }

    // Bytes after the last frame the model reads: a pad or a trailer the specification
    // leaves out. Kept and written back, so not a failure, but worth knowing about.
    if (!decoded.trailer().empty() && ++tally.trailing <= shown) {
        std::cerr << "read " << number << ": " << decoded.trailer().size() << " bytes after the last frame\n";
    }

    // The round trip. Encode derives the count, every length and every code again from the
    // messages, so the bytes agree with the wire only when every rule does.
    try {
        encoded.assign(decoded.encoded_size(), std::byte{ 0 });
        const std::size_t written = decoded.encode(encoded.data(), encoded.size());
        const std::size_t offset = first_difference(frame.payload, frame.payload_len, encoded.data(), written);

        if ((written != frame.payload_len || offset < written) && ++tally.mismatched <= shown) {
            std::cerr << "read " << number << ": encodes to " << written << " bytes against " << frame.payload_len
                      << " read, first difference at byte " << offset << ' '
                      << place(decoded.frames(), frames_begin(decoded.frames(), written - decoded.trailer().size()), offset) << '\n';
        }
    } catch (const protocol::EncodeError& error) {
        if (++tally.mismatched <= shown) {
            std::cerr << "read " << number << ": does not encode: " << error.what() << '\n';
        }
    }
}

// Client Packet: a connection's bytes, as far as they amount to whole frames.
void read_client_packet(std::vector<std::byte>& buffer, Tally& tally, std::vector<std::byte>& encoded) {
    protocol::ClientPacket decoded;
    std::size_t consumed = 0;

    try {
        consumed = decoded.decode(buffer.data(), buffer.size());
    } catch (const protocol::DecodeError& error) {
        const std::size_t number = ++tally.packets;

        if (++tally.undecodable <= shown) {
            std::cerr << "read " << number << ": does not decode: " << error.what() << '\n';
        }
        buffer.clear();
        return;
    }

    if (consumed == 0) { return; }

    const std::size_t number = ++tally.packets;

    std::size_t index = 0;

    for (const auto& held : decoded.frames()) {
        ++index;
        const protocol::Message* message = held.message();

        if (message == nullptr) { continue; }

        ++tally.messages;

        // The size rule: the length the frame's header declares against what the model reads.
        const std::size_t declared = static_cast<std::size_t>(held.client_packet_header().packet_length()) + 2;
        const std::size_t derived = frame_size(held);

        if (declared != derived && ++tally.sizes <= shown) {
            std::cerr << "read " << number << " frame " << index << " (" << message->name() << "): declares "
                      << declared << " bytes, the model reads " << derived << '\n';
        }

        // The dispatch: a code the specification does not list, or one that selected
        // a message whose own code is another.
        if (const auto* stranger = dynamic_cast<const protocol::UnknownMessage*>(message)) {
            const std::uint64_t value = code_value(stranger->type());

            ++tally.codes[value];

            if (++tally.unknown <= shown) {
                std::cerr << "read " << number << " frame " << index << ": unknown message code " << value << '\n';
            }
        } else if (message->type() != held.client_packet_header().client_packet_type()) {
            if (++tally.dispatches <= shown) {
                std::cerr << "read " << number << " frame " << index << ": code " << code_value(held.client_packet_header().client_packet_type())
                          << " decoded as " << message->name() << ", whose code is " << code_value(message->type()) << '\n';
            }
        }
    }

    // The round trip. Encode derives the count, every length and every code again from the
    // messages, so the bytes agree with the wire only when every rule does.
    try {
        encoded.assign(decoded.encoded_size(), std::byte{ 0 });
        const std::size_t written = decoded.encode(encoded.data(), encoded.size());
        const std::size_t offset = first_difference(buffer.data(), consumed, encoded.data(), written);

        if ((written != consumed || offset < written) && ++tally.mismatched <= shown) {
            std::cerr << "read " << number << ": encodes to " << written << " bytes against " << consumed
                      << " read, first difference at byte " << offset << ' '
                      << place(decoded.frames(), 0, offset) << '\n';
        }
    } catch (const protocol::EncodeError& error) {
        if (++tally.mismatched <= shown) {
            std::cerr << "read " << number << ": does not encode: " << error.what() << '\n';
        }
    }

    buffer.erase(buffer.begin(), buffer.begin() + static_cast<std::ptrdiff_t>(consumed));
}

// Server Packet: a connection's bytes, as far as they amount to whole frames.
void read_server_packet(std::vector<std::byte>& buffer, Tally& tally, std::vector<std::byte>& encoded) {
    protocol::ServerPacket decoded;
    std::size_t consumed = 0;

    try {
        consumed = decoded.decode(buffer.data(), buffer.size());
    } catch (const protocol::DecodeError& error) {
        const std::size_t number = ++tally.packets;

        if (++tally.undecodable <= shown) {
            std::cerr << "read " << number << ": does not decode: " << error.what() << '\n';
        }
        buffer.clear();
        return;
    }

    if (consumed == 0) { return; }

    const std::size_t number = ++tally.packets;

    std::size_t index = 0;

    for (const auto& held : decoded.frames()) {
        ++index;
        const protocol::ServerMessage* message = held.message();

        if (message == nullptr) { continue; }

        ++tally.messages;

        // The size rule: the length the frame's header declares against what the model reads.
        const std::size_t declared = static_cast<std::size_t>(held.server_packet_header().packet_length()) + 2;
        const std::size_t derived = frame_size(held);

        if (declared != derived && ++tally.sizes <= shown) {
            std::cerr << "read " << number << " frame " << index << " (" << message->name() << "): declares "
                      << declared << " bytes, the model reads " << derived << '\n';
        }

        // The dispatch: a code the specification does not list, or one that selected
        // a message whose own code is another.
        if (const auto* stranger = dynamic_cast<const protocol::UnknownServerMessage*>(message)) {
            const std::uint64_t value = code_value(stranger->type());

            ++tally.codes[value];

            if (++tally.unknown <= shown) {
                std::cerr << "read " << number << " frame " << index << ": unknown message code " << value << '\n';
            }
        } else if (message->type() != held.server_packet_header().server_packet_type()) {
            if (++tally.dispatches <= shown) {
                std::cerr << "read " << number << " frame " << index << ": code " << code_value(held.server_packet_header().server_packet_type())
                          << " decoded as " << message->name() << ", whose code is " << code_value(message->type()) << '\n';
            }
        }
    }

    // The round trip. Encode derives the count, every length and every code again from the
    // messages, so the bytes agree with the wire only when every rule does.
    try {
        encoded.assign(decoded.encoded_size(), std::byte{ 0 });
        const std::size_t written = decoded.encode(encoded.data(), encoded.size());
        const std::size_t offset = first_difference(buffer.data(), consumed, encoded.data(), written);

        if ((written != consumed || offset < written) && ++tally.mismatched <= shown) {
            std::cerr << "read " << number << ": encodes to " << written << " bytes against " << consumed
                      << " read, first difference at byte " << offset << ' '
                      << place(decoded.frames(), 0, offset) << '\n';
        }
    } catch (const protocol::EncodeError& error) {
        if (++tally.mismatched <= shown) {
            std::cerr << "read " << number << ": does not encode: " << error.what() << '\n';
        }
    }

    buffer.erase(buffer.begin(), buffer.begin() + static_cast<std::ptrdiff_t>(consumed));
}

} // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    std::vector<std::byte> encoded;
    Tally tally;

    // One read per tree for the whole capture, reused the way a program reads one, so
    // state a failed decode leaves behind shows up here too.
    protocol::Packet packet_read;

    // Which endpoint of each connection was dialled, learned from the handshake as it goes by.
    Sides sides;

    // One buffer per connection: the reassembler hands over the bytes in order, and what
    // does not yet amount to a whole frame waits here for the bytes behind it.
    std::unordered_map<packet::TcpFlowKey, std::vector<std::byte>, packet::TcpFlowKey::hash> buffers;

    packet::TcpReassembler reassembler;

    reassembler.on_data = [&](const packet::TcpFlowKey& key, const std::byte* data, std::size_t length) {
        std::vector<std::byte>& buffer = buffers[key];

        buffer.insert(buffer.end(), data, data + length);

        if (sides.from_server(key.src_ip, key.src_port, key.dst_ip, key.dst_port)) {
            read_server_packet(buffer, tally, encoded);
            return;
        }

        read_client_packet(buffer, tally, encoded);
    };

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        if (frame.is_udp()) {
            read_packet(packet_read, frame, tally, encoded);
            continue;
        }

        if (frame.is_tcp()) {
            sides.saw(frame);
            reassembler.process(frame);
        }

    }

    // A capture that ends mid-frame leaves bytes behind: not a failure, but reported.
    std::size_t unread = 0;

    for (const auto& [key, buffer] : buffers) { unread += buffer.size(); }

    if (unread > 0) {
        std::fprintf(stderr, "%zu bytes left unread at the end of the capture\n", unread);
    }

    if (sides.unknown > 0) {
        std::fprintf(stderr, "%zu reads on connections whose handshake the capture missed, read as the client's\n", sides.unknown);
    }

    summarize(tally);

    return tally.failed() ? 1 : 0;
}
