// Jpx.TseEquities.MarketByOrder.Flex.v1.1 field dump.
//
// Generated by Scaled.Historical.Dump.Cpp — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/classes/jpx/tseequities/marketbyorder/flex/v1.1/definitions.hpp"

namespace protocol = ::jpx::tseequities::marketbyorder::flex::v1_1;

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);
    protocol::UdpPacket decoded;
    std::size_t messages = 0;
    std::size_t undecodable = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        try {
            decoded.decode(frame.payload, frame.payload_len);
        } catch (const protocol::DecodeError& error) {
            ++undecodable;
            std::cerr << "undecodable datagram: " << error.what() << '\n';
            continue;
        }

        for (const protocol::Frame& held : decoded.frames()) {
            if (held.message() == nullptr) { continue; }
            ++messages;
            std::cout << *held.message() << '\n';
        }
    }

    std::fprintf(stderr, "%zu messages\n", messages);

    if (undecodable > 0) {
        std::fprintf(stderr, "%zu undecodable datagrams\n", undecodable);
    }

    return 0;
}
