// B3.B3Derivatives.BinaryUmdf.Sbe.v1.9 field dump.
//
// Generated by Scaled.Historical.Dump.Cpp — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/classes/b3/b3derivatives/binaryumdf/sbe/v1.9/definitions.hpp"

namespace protocol = ::b3::b3derivatives::binaryumdf::sbe::v1_9;

namespace {

// Every message a read frames, printed through the message's own print. A tree's frame class
// is its own, so the frames are taken as they come rather than by naming their type.
constexpr auto framed = [](const auto& read) {
    std::size_t messages = 0;

    for (const auto& held : read.frames()) {
        if (held.message() == nullptr) { continue; }

        ++messages;
        std::cout << *held.message() << '\n';
    }

    return messages;
};

// A frame that arrives whole is a whole packet: what it does not hold belongs to no other frame.
template <typename Read, typename Printer>
std::size_t whole(const packet::Frame& frame, std::size_t& undecodable, Printer printer) {
    Read decoded;

    try {
        decoded.decode(frame.payload, frame.payload_len);
    } catch (const protocol::DecodeError& error) {
        ++undecodable;
        std::cerr << "undecodable frame: " << error.what() << '\n';
        return 0;
    }

    return printer(decoded);
}

}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <capture.pcap>\n", argv[0]);
        return 2;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);

    std::size_t messages = 0;
    std::size_t undecodable = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        if (frame.is_udp()) {
            messages += whole<protocol::Packet>(frame, undecodable, framed);
            continue;
        }
    }

    std::fprintf(stderr, "%zu messages\n", messages);

    if (undecodable > 0) {
        std::fprintf(stderr, "%zu reads did not decode\n", undecodable);
    }

    return 0;
}
