#pragma once

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <ostream>
#include <string_view>

#include "../common/Decimal.hpp"
#include "../enums/ModificationFlag.hpp"
#include "../enums/OrderCondition.hpp"
#include "../enums/Side.hpp"
#include "../messages/Message.hpp"

namespace jpx::tseequities::marketbyorder::flex::v1_1 {

class Visitor;

// Provides information about book registration. Delivered when a new order or modification
// order is registered.
class AddOrderMessage : public Message {
  public:
    // The code that selects this message
    static constexpr MessageCode message_type = MessageType::AddOrderMessage;
    // Bytes of this message on the wire
    static constexpr std::size_t wire_size = 25;

    AddOrderMessage() = default;
    AddOrderMessage(std::chrono::microseconds time_microseconds, std::uint32_t order_id, Side side, std::uint64_t quantity, std::optional<Decimal> price, OrderCondition order_condition, ModificationFlag modification_flag);

    // Time Microseconds: Time to the nearest microsecond
    std::chrono::microseconds time_microseconds() const;
    void set_time_microseconds(std::chrono::microseconds value);

    // Order Id: Identifier assigned per issue on an order basis, unique and sequential each
    // business day
    std::uint32_t order_id() const;
    void set_order_id(std::uint32_t value);

    // Side: Indicates buy or sell
    Side side() const;
    void set_side(Side value);

    // Quantity: Order quantity registered on the order book in number of shares
    std::uint64_t quantity() const;
    void set_quantity(std::uint64_t value);

    // Price: Price registered on the order book; for market orders set to the maximum 64-bit
    // value
    std::optional<Decimal> price() const;
    void set_price(std::optional<Decimal> value);

    // Order Condition: Indicates the order condition
    OrderCondition order_condition() const;
    void set_order_condition(OrderCondition value);

    // Modification Flag: When the A tag is generated by a modification order, indicates
    // whether there is a change of time priority
    ModificationFlag modification_flag() const;
    void set_modification_flag(ModificationFlag value);

    // Message
    MessageCode type() const override;
    std::string_view name() const override;
    std::size_t decode(const std::byte* data, std::size_t length) override;
    std::size_t encode(std::byte* data, std::size_t capacity) const override;
    std::size_t encoded_size() const override;
    void accept(Visitor& visitor) const override;
    std::unique_ptr<Message> clone() const override;
    void print(std::ostream& out) const override;
    bool equals(const Message& other) const override;

    bool operator==(const AddOrderMessage& other) const;
    bool operator!=(const AddOrderMessage& other) const;

  private:
    std::chrono::microseconds time_microseconds_{};
    std::uint32_t order_id_{};
    Side side_{};
    std::uint64_t quantity_{};
    std::optional<Decimal> price_{};
    OrderCondition order_condition_{};
    ModificationFlag modification_flag_{};
};

} // namespace jpx::tseequities::marketbyorder::flex::v1_1
