#pragma once

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <ostream>
#include <string_view>

#include "../enums/ModificationFlag.hpp"
#include "../enums/Side.hpp"
#include "../messages/Message.hpp"

namespace jpx::tseequities::marketbyorder::flex::v1_1 {

class Visitor;

// Provides information about order deletion from the order book. Delivered when an order is
// deleted via a cancel order or a modification order or when a registered order expires.
class OrderDeleteMessage : public Message {
  public:
    // The code that selects this message
    static constexpr MessageCode message_type = MessageType::OrderDeleteMessage;
    // Bytes of this message on the wire
    static constexpr std::size_t wire_size = 10;

    OrderDeleteMessage() = default;
    OrderDeleteMessage(std::chrono::microseconds time_microseconds, std::uint32_t order_id, Side side, ModificationFlag modification_flag);

    // Time Microseconds: Time to the nearest microsecond
    std::chrono::microseconds time_microseconds() const;
    void set_time_microseconds(std::chrono::microseconds value);

    // Order Id: Identifier assigned per issue on an order basis, unique and sequential each
    // business day
    std::uint32_t order_id() const;
    void set_order_id(std::uint32_t value);

    // Side: Indicates buy or sell
    Side side() const;
    void set_side(Side value);

    // Modification Flag: When the A tag is generated by a modification order, indicates
    // whether there is a change of time priority
    ModificationFlag modification_flag() const;
    void set_modification_flag(ModificationFlag value);

    // Message
    MessageCode type() const override;
    std::string_view name() const override;
    std::size_t decode(const std::byte* data, std::size_t length) override;
    std::size_t encode(std::byte* data, std::size_t capacity) const override;
    std::size_t encoded_size() const override;
    void accept(Visitor& visitor) const override;
    std::unique_ptr<Message> clone() const override;
    void print(std::ostream& out) const override;
    bool equals(const Message& other) const override;

    bool operator==(const OrderDeleteMessage& other) const;
    bool operator!=(const OrderDeleteMessage& other) const;

  private:
    std::chrono::microseconds time_microseconds_{};
    std::uint32_t order_id_{};
    Side side_{};
    ModificationFlag modification_flag_{};
};

} // namespace jpx::tseequities::marketbyorder::flex::v1_1
