#pragma once

#include <bit>
#include <cstddef>
#include <cstdint>

namespace jpx::tseequities::marketbyorder::flex::v1_1 {


// When the A tag is generated by a modification order, indicates whether there is a change of time priority
struct ModificationFlag {

    static constexpr auto name = "Modification Flag";
    static constexpr std::size_t size = 1;
    using type = std::uint8_t;

    // default constructor
    constexpr ModificationFlag()
     : value{ 0 } {}

    // standard constructor
    constexpr explicit ModificationFlag(const std::uint8_t &value)
     : value{ value } {}

    // get value of ModificationFlag field
    [[nodiscard]] std::uint8_t get() const {
        return value;
    }

  protected:
    std::uint8_t value;
};
}
