#pragma once

#include <cstddef>
#include <cstdint>

namespace jpx::tseequities::marketbyorder::flex::v1_1 {


// Indicates whether another packet follows that was generated by the same transaction
struct UtilityFlag {

    static constexpr auto name = "Utility Flag";
    static constexpr std::size_t size = 1;
    using type = std::uint8_t;

    // default constructor
    constexpr UtilityFlag()
     : value{ 0 } {}

    // standard constructor
    constexpr explicit UtilityFlag(const std::uint8_t &value)
     : value{ value } {}

    // get value of UtilityFlag field
    [[nodiscard]] std::uint8_t get() const {
        return value;
    }

  protected:
    std::uint8_t value;
};
}
