// Generated by Scaled.Historical.Extractor.Cpp — packet sampling logic for Iex.IexEquities.Tops.Snap.v1.6.
#pragma once

#include "../pcap/Frame.hpp"
#include "../pcap/PcapFile.hpp"
#include "../pcap/TcpReassembler.hpp"
#include "cpp/modern/iex/iexequities/tops/snap/v1.6/definitions.hpp"
#include "../protocol/Branches.hpp"

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <map>
#include <optional>
#include <string>
#include <type_traits>
#include <vector>
#include <deque>
#include <unordered_map>
#include <utility>

namespace extractor {

namespace fs = std::filesystem;

// One captured frame held end-to-end so we can rewrite it later.
struct Captured {
    std::uint64_t timestamp_ns = 0;
    std::vector<std::uint8_t> bytes;
};

// Minimal libpcap-format writer (microsecond timestamps, LINKTYPE_ETHERNET).
inline void write_pcap(const fs::path& out, const std::vector<const Captured*>& frames) {
    std::ofstream f(out, std::ios::binary);
    if (!f) { std::fprintf(stderr, "open(%s) failed\n", out.string().c_str()); return; }

    auto write_u32 = [&](std::uint32_t v) { f.write(reinterpret_cast<const char*>(&v), 4); };
    auto write_u16 = [&](std::uint16_t v) { f.write(reinterpret_cast<const char*>(&v), 2); };

    write_u32(0xa1b2c3d4);  // magic — microsecond timestamps, host endian
    write_u16(2); write_u16(4);   // version 2.4
    write_u32(0);                  // thiszone
    write_u32(0);                  // sigfigs
    write_u32(65535);              // snaplen
    write_u32(1);                  // network = LINKTYPE_ETHERNET

    for (const Captured* c : frames) {
        const std::uint64_t ts = c->timestamp_ns;
        write_u32(static_cast<std::uint32_t>(ts / 1'000'000'000ull));
        write_u32(static_cast<std::uint32_t>((ts % 1'000'000'000ull) / 1000ull));
        write_u32(static_cast<std::uint32_t>(c->bytes.size()));
        write_u32(static_cast<std::uint32_t>(c->bytes.size()));
        f.write(reinterpret_cast<const char*>(c->bytes.data()), c->bytes.size());
    }
}

inline Captured capture_of(const packet::PcapFile& pcap) {
    Captured c;
    c.timestamp_ns = pcap.timestamp_ns();
    const auto* p = reinterpret_cast<const std::uint8_t*>(pcap.data());
    c.bytes.assign(p, p + pcap.length());
    return c;
}

// Wrap a SoupBin packet's raw bytes in a synthetic Ethernet + IPv4 + TCP frame so each per-key
// sample is replayable through a parser pipeline expecting wire framing. The original wire
// frame is not a usable single-frame sample for TCP/SoupBin because the SoupBin packet rarely
// starts at TCP-payload-offset-0 (it usually lives mid-segment after preceding packets, and
// often spans multiple segments). The synthetic frame puts the SoupBin packet at offset 0,
// stripping the realism in exchange for self-containment.
inline Captured synthesize_wire_frame(std::uint64_t timestamp_ns,
                                      const std::uint8_t* payload, std::size_t payload_len) {
    Captured c;
    c.timestamp_ns = timestamp_ns;
    const std::size_t ip_total_len = 20 + 20 + payload_len;
    c.bytes.reserve(14 + ip_total_len);

    // Ethernet: zero MACs, ethertype IPv4.
    for (int i = 0; i < 12; ++i) { c.bytes.push_back(0); }
    c.bytes.push_back(0x08); c.bytes.push_back(0x00);

    // IPv4: version 4, IHL 5, no options, no fragmentation, TTL 64, proto TCP, zero checksum.
    c.bytes.push_back(0x45);
    c.bytes.push_back(0x00);
    c.bytes.push_back(static_cast<std::uint8_t>((ip_total_len >> 8) & 0xff));
    c.bytes.push_back(static_cast<std::uint8_t>(ip_total_len & 0xff));
    for (int i = 0; i < 4; ++i) { c.bytes.push_back(0); }
    c.bytes.push_back(64);
    c.bytes.push_back(6);
    c.bytes.push_back(0); c.bytes.push_back(0);
    for (int i = 0; i < 8; ++i) { c.bytes.push_back(0); }

    // TCP: zero ports/seq/ack, data offset 5 (no options), ACK flag, max window, zero checksum.
    for (int i = 0; i < 4; ++i) { c.bytes.push_back(0); }
    for (int i = 0; i < 8; ++i) { c.bytes.push_back(0); }
    c.bytes.push_back(0x50);
    c.bytes.push_back(0x10);
    c.bytes.push_back(0xff); c.bytes.push_back(0xff);
    c.bytes.push_back(0); c.bytes.push_back(0);
    c.bytes.push_back(0); c.bytes.push_back(0);

    c.bytes.insert(c.bytes.end(), payload, payload + payload_len);
    return c;
}

// A sample for one discriminator key — one or more wire frames that together carry the
// message. UDP messages always produce a single-frame sample. TCP/SoupBin per-key samples
// are single synthetic frames; the Reassembly.pcap exemplar holds the multi-frame real case.
struct PacketSample {
    std::vector<Captured> frames;
    std::size_t total_bytes = 0;
};

inline PacketSample sample_of_one(Captured frame) {
    PacketSample s;
    s.total_bytes = frame.bytes.size();
    s.frames.push_back(std::move(frame));
    return s;
}

inline PacketSample sample_of_many(std::vector<Captured> frames) {
    PacketSample s;
    s.frames = std::move(frames);
    for (const auto& f : s.frames) { s.total_bytes += f.bytes.size(); }
    return s;
}

// Write each per-key sample as its own pcap (one or more frames) plus a roll-up and the two
// diagnostic exemplars.
//   Sample.pcap            — every per-key sample concatenated, in one pcap.
//   MultipleMessages.pcap  — first wire frame that carried more than one application message
//                            (UDP: count > 1 in the packet header; TCP: >1 SoupBin packet in a single chunk).
//   Reassembly.pcap        — TCP only — the sequence of wire frames that, taken together, deliver one
//                            SoupBin packet whose bytes span multiple TCP segments.
inline void write_samples(const fs::path& out_dir,
                          const std::map<std::uint64_t, PacketSample>& smallest,
                          const std::optional<Captured>& multiple_messages,
                          const std::vector<Captured>& reassembly_frames) {
    fs::create_directories(out_dir);

    std::vector<const Captured*> roll_up;
    for (const auto& [id, sample] : smallest) {
        const char* name = protocol::Branches::name(id);
        char fallback[32];
        if (!name) { std::snprintf(fallback, sizeof fallback, "branch_%llu", static_cast<unsigned long long>(id)); name = fallback; }

        std::vector<const Captured*> ptrs;
        ptrs.reserve(sample.frames.size());
        for (const auto& f : sample.frames) { ptrs.push_back(&f); roll_up.push_back(&f); }
        write_pcap(out_dir / (std::string(name) + ".pcap"), ptrs);
    }
    write_pcap(out_dir / "Sample.pcap", roll_up);

    if (multiple_messages) {
        write_pcap(out_dir / "MultipleMessages.pcap", { &*multiple_messages });
    }

    if (!reassembly_frames.empty()) {
        std::vector<const Captured*> ptrs;
        ptrs.reserve(reassembly_frames.size());
        for (const auto& f : reassembly_frames) { ptrs.push_back(&f); }
        write_pcap(out_dir / "Reassembly.pcap", ptrs);
    }
}

// Per-flow accumulator. The reassembler delivers in-order chunks; a packet may straddle chunk
// boundaries, so each flow holds its leftover bytes and packets are walked out of them greedily.
// The wire_log records which wire frame each leftover byte came from — when a packet's bytes
// span more than one wire frame, that's a reassembly example.
struct FlowBuffer {
    std::vector<std::uint8_t> bytes;
    // (wire_frame, byte_count) entries, front-to-back, parallel to `bytes`.
    // Consecutive entries from the same wire frame are merged so contributors are unique.
    std::deque<std::pair<Captured, std::size_t>> wire_log;
};

// A discriminator value as a key: its bits, never sign-extended.
template <typename Value>
inline std::uint64_t key_of(Value value) {
    return static_cast<std::uint64_t>(static_cast<std::make_unsigned_t<Value>>(value));
}

inline int sample(const fs::path& in_path, const fs::path& out_dir) {
    packet::PcapFile pcap(in_path.string());

    std::map<std::uint64_t, PacketSample> smallest;   // smallest sample per key
    std::optional<Captured> multiple_messages;        // first wire frame carrying more than one message
    std::vector<Captured> reassembly_frames;          // wire frames that together delivered one reassembled packet
    Captured current_wire;                            // wire frame being walked

    // Keep a sample for a key when it is the first or smaller than the one kept.
    auto keep = [&](std::uint64_t id, std::size_t size, auto make) {
        const auto it = smallest.find(id);
        if (it == smallest.end() || size < it->second.total_bytes) { smallest[id] = sample_of_one(make()); }
    };

    // The Packet tree: MessageIterator walks each flow's reassembled bytes.
    std::unordered_map<packet::TcpFlowKey, FlowBuffer, packet::TcpFlowKey::hash> flows_message;
    packet::TcpReassembler reassembler_message;
    reassembler_message.on_data = [&](const packet::TcpFlowKey& key, const std::byte* data, std::size_t len) {
        auto& flow = flows_message[key];

        // Append bytes + record contribution. Merge with the trailing log entry when it's
        // the same wire frame (out-of-order drains can trigger multiple on_data per process()).
        flow.bytes.insert(flow.bytes.end(),
                          reinterpret_cast<const std::uint8_t*>(data),
                          reinterpret_cast<const std::uint8_t*>(data) + len);
        if (!flow.wire_log.empty() &&
            flow.wire_log.back().first.timestamp_ns == current_wire.timestamp_ns) {
            flow.wire_log.back().second += len;
        } else {
            flow.wire_log.emplace_back(current_wire, len);
        }

        const auto* base = reinterpret_cast<const std::byte*>(flow.bytes.data());
        iex::iexequities::tops::snap::v1_6::MessageIterator packets;
        packets.initialize(base, flow.bytes.size());

        std::size_t pos = 0;
        std::size_t packets_in_chunk = 0;
        while (packets.next()) {
            if (packets.current > packets.end) { break; }   // need more bytes

            const std::size_t begin = pos;
            pos = static_cast<std::size_t>(packets.current - base);
            const std::size_t span = pos - begin;
            if (packets.message > packets.current) { continue; }   // shorter than its header (a null sentinel)

            std::uint64_t id = key_of(packets.message_type);
            switch (id) {
                case 100:
                    if (packets.message + sizeof(iex::iexequities::tops::snap::v1_6::SnapshotDataMessage) <= packets.current) {
                        id = (id << 32) | key_of(iex::iexequities::tops::snap::v1_6::SnapshotDataMessage::parse(packets.message)->iex_tp_message_type.get());
                    }
                    break;
                default:
                    break;
            }

            // Per-key sample: a synthetic wire frame around the packet's raw bytes, so the packet sits
            // at TCP-payload offset 0 and the per-message pcap replays standalone.
            const auto* bytes = flow.bytes.data() + begin;
            keep(id, 14 + 20 + 20 + span, [&] { return synthesize_wire_frame(current_wire.timestamp_ns, bytes, span); });

            // Reassembly example: the original wire frames of the first packet spanning more than one.
            if (reassembly_frames.empty()) {
                std::vector<Captured> contributors;
                std::size_t walked = 0;
                for (const auto& [frame, count] : flow.wire_log) {
                    if (walked >= begin + span) { break; }
                    if (walked + count > begin) { contributors.push_back(frame); }
                    walked += count;
                }
                if (contributors.size() > 1) { reassembly_frames = std::move(contributors); }
            }

            ++packets_in_chunk;
        }

        // Drop consumed bytes from both buffer and contribution log in lock-step.
        if (pos > 0) {
            flow.bytes.erase(flow.bytes.begin(), flow.bytes.begin() + static_cast<std::ptrdiff_t>(pos));
            std::size_t remaining = pos;
            while (remaining > 0 && !flow.wire_log.empty()) {
                auto& [frame, count] = flow.wire_log.front();
                if (count <= remaining) { remaining -= count; flow.wire_log.pop_front(); }
                else { count -= remaining; remaining = 0; }
            }
        }

        if (packets_in_chunk > 1 && !multiple_messages) { multiple_messages = current_wire; }
    };

    while (pcap.advance()) {
        packet::Frame frame(pcap.data(), pcap.length());
        if (!frame.valid()) { continue; }

        if (frame.is_tcp()) {
            current_wire = capture_of(pcap);
            reassembler_message.process(frame);
        }
    }

    write_samples(out_dir, smallest, multiple_messages, reassembly_frames);

    std::fprintf(stderr, "sampled %zu unique keys from %s -> %s\n",
                 smallest.size(), in_path.string().c_str(), out_dir.string().c_str());
    return 0;
}

} // namespace extractor
