// Generated by Scaled.Historical.Extractor.Cpp — packet sampling logic for Iex.IexEquities.Tops.Snap.v1.6.
#pragma once

#include "../pcap/Frame.hpp"
#include "../pcap/PcapFile.hpp"
#include "../pcap/TcpReassembler.hpp"
#include "../protocol/Branches.hpp"

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <map>
#include <optional>
#include <string>
#include <vector>
#include <deque>
#include <unordered_map>
#include <utility>

namespace extractor {

namespace fs = std::filesystem;

// One captured frame held end-to-end so we can rewrite it later.
struct Captured {
    std::uint64_t timestamp_ns = 0;
    std::vector<std::uint8_t> bytes;
};

// Minimal libpcap-format writer (microsecond timestamps, LINKTYPE_ETHERNET).
inline void write_pcap(const fs::path& out, const std::vector<const Captured*>& frames) {
    std::ofstream f(out, std::ios::binary);
    if (!f) { std::fprintf(stderr, "open(%s) failed\n", out.string().c_str()); return; }

    auto write_u32 = [&](std::uint32_t v) { f.write(reinterpret_cast<const char*>(&v), 4); };
    auto write_u16 = [&](std::uint16_t v) { f.write(reinterpret_cast<const char*>(&v), 2); };

    write_u32(0xa1b2c3d4);  // magic — microsecond timestamps, host endian
    write_u16(2); write_u16(4);   // version 2.4
    write_u32(0);                  // thiszone
    write_u32(0);                  // sigfigs
    write_u32(65535);              // snaplen
    write_u32(1);                  // network = LINKTYPE_ETHERNET

    for (const Captured* c : frames) {
        const std::uint64_t ts = c->timestamp_ns;
        write_u32(static_cast<std::uint32_t>(ts / 1'000'000'000ull));
        write_u32(static_cast<std::uint32_t>((ts % 1'000'000'000ull) / 1000ull));
        write_u32(static_cast<std::uint32_t>(c->bytes.size()));
        write_u32(static_cast<std::uint32_t>(c->bytes.size()));
        f.write(reinterpret_cast<const char*>(c->bytes.data()), c->bytes.size());
    }
}

inline Captured capture_of(const packet::PcapFile& pcap) {
    Captured c;
    c.timestamp_ns = pcap.timestamp_ns();
    const auto* p = reinterpret_cast<const std::uint8_t*>(pcap.data());
    c.bytes.assign(p, p + pcap.length());
    return c;
}

// Wrap a SoupBin packet's raw bytes in a synthetic Ethernet + IPv4 + TCP frame so each per-key
// sample is replayable through a parser pipeline expecting wire framing. The original wire
// frame is not a usable single-frame sample for TCP/SoupBin because the SoupBin packet rarely
// starts at TCP-payload-offset-0 (it usually lives mid-segment after preceding packets, and
// often spans multiple segments). The synthetic frame puts the SoupBin packet at offset 0,
// stripping the realism in exchange for self-containment.
inline Captured synthesize_wire_frame(std::uint64_t timestamp_ns,
                                      const std::uint8_t* payload, std::size_t payload_len) {
    Captured c;
    c.timestamp_ns = timestamp_ns;
    const std::size_t ip_total_len = 20 + 20 + payload_len;
    c.bytes.reserve(14 + ip_total_len);

    // Ethernet: zero MACs, ethertype IPv4.
    for (int i = 0; i < 12; ++i) { c.bytes.push_back(0); }
    c.bytes.push_back(0x08); c.bytes.push_back(0x00);

    // IPv4: version 4, IHL 5, no options, no fragmentation, TTL 64, proto TCP, zero checksum.
    c.bytes.push_back(0x45);
    c.bytes.push_back(0x00);
    c.bytes.push_back(static_cast<std::uint8_t>((ip_total_len >> 8) & 0xff));
    c.bytes.push_back(static_cast<std::uint8_t>(ip_total_len & 0xff));
    for (int i = 0; i < 4; ++i) { c.bytes.push_back(0); }
    c.bytes.push_back(64);
    c.bytes.push_back(6);
    c.bytes.push_back(0); c.bytes.push_back(0);
    for (int i = 0; i < 8; ++i) { c.bytes.push_back(0); }

    // TCP: zero ports/seq/ack, data offset 5 (no options), ACK flag, max window, zero checksum.
    for (int i = 0; i < 4; ++i) { c.bytes.push_back(0); }
    for (int i = 0; i < 8; ++i) { c.bytes.push_back(0); }
    c.bytes.push_back(0x50);
    c.bytes.push_back(0x10);
    c.bytes.push_back(0xff); c.bytes.push_back(0xff);
    c.bytes.push_back(0); c.bytes.push_back(0);
    c.bytes.push_back(0); c.bytes.push_back(0);

    c.bytes.insert(c.bytes.end(), payload, payload + payload_len);
    return c;
}

// A sample for one discriminator key — one or more wire frames that together carry the
// message. UDP messages always produce a single-frame sample. TCP/SoupBin per-key samples
// are single synthetic frames; the Reassembly.pcap exemplar holds the multi-frame real case.
struct PacketSample {
    std::vector<Captured> frames;
    std::size_t total_bytes = 0;
};

inline PacketSample sample_of_one(Captured frame) {
    PacketSample s;
    s.total_bytes = frame.bytes.size();
    s.frames.push_back(std::move(frame));
    return s;
}

inline PacketSample sample_of_many(std::vector<Captured> frames) {
    PacketSample s;
    s.frames = std::move(frames);
    for (const auto& f : s.frames) { s.total_bytes += f.bytes.size(); }
    return s;
}

// Write each per-key sample as its own pcap (one or more frames) plus a roll-up and the two
// diagnostic exemplars.
//   Sample.pcap            — every per-key sample concatenated, in one pcap.
//   MultipleMessages.pcap  — first wire frame that carried more than one application message
//                            (UDP: count > 1 in the packet header; TCP: >1 SoupBin packet in a single chunk).
//   Reassembly.pcap        — TCP only — the sequence of wire frames that, taken together, deliver one
//                            SoupBin packet whose bytes span multiple TCP segments.
inline void write_samples(const fs::path& out_dir,
                          const std::map<std::uint64_t, PacketSample>& smallest,
                          const std::optional<Captured>& multiple_messages,
                          const std::vector<Captured>& reassembly_frames) {
    fs::create_directories(out_dir);

    std::vector<const Captured*> roll_up;
    for (const auto& [id, sample] : smallest) {
        const char* name = protocol::Branches::name(id);
        char fallback[32];
        if (!name) { std::snprintf(fallback, sizeof fallback, "branch_%llu", static_cast<unsigned long long>(id)); name = fallback; }

        std::vector<const Captured*> ptrs;
        ptrs.reserve(sample.frames.size());
        for (const auto& f : sample.frames) { ptrs.push_back(&f); roll_up.push_back(&f); }
        write_pcap(out_dir / (std::string(name) + ".pcap"), ptrs);
    }
    write_pcap(out_dir / "Sample.pcap", roll_up);

    if (multiple_messages) {
        write_pcap(out_dir / "MultipleMessages.pcap", { &*multiple_messages });
    }

    if (!reassembly_frames.empty()) {
        std::vector<const Captured*> ptrs;
        ptrs.reserve(reassembly_frames.size());
        for (const auto& f : reassembly_frames) { ptrs.push_back(&f); }
        write_pcap(out_dir / "Reassembly.pcap", ptrs);
    }
}

// Per-flow accumulator. The reassembler delivers in-order chunks; a SoupBin packet may
// straddle chunk boundaries, so we hold a leftover-bytes buffer per flow and parse packets
// out of it greedily. The wire_log records which wire frame each leftover byte came from —
// when a SoupBin packet's bytes span more than one wire frame, that's a reassembly example.
struct FlowBuffer {
    std::vector<std::uint8_t> bytes;
    // (wire_frame, byte_count) entries, front-to-back, parallel to `bytes`.
    // Consecutive entries from the same wire frame are merged so contributors are unique.
    std::deque<std::pair<Captured, std::size_t>> wire_log;
};

inline int sample(const fs::path& in_path, const fs::path& out_dir) {
    packet::PcapFile pcap(in_path.string());

    std::map<std::uint64_t, PacketSample> smallest;   // smallest synthetic wire frame per discriminator key
    std::optional<Captured> multiple_messages;        // first wire frame whose chunk produced >1 SoupBin packet
    std::vector<Captured> reassembly_frames;          // wire frames that together delivered one reassembled SoupBin packet
    Captured current_wire;                            // wire frame driving the reassembler's current process() call

    std::unordered_map<packet::TcpFlowKey, FlowBuffer, packet::TcpFlowKey::hash> flows;

    // outer packet types whose body holds a nested application-message dispatch
    auto is_data_bearing = [](std::uint8_t outer) -> bool {
        switch (outer) {
            case 100: return true;
            default: return false;
        }
    };

    packet::TcpReassembler reassembler;
    reassembler.on_data = [&](const packet::TcpFlowKey& key, const std::byte* data, std::size_t len) {
        auto& flow = flows[key];

        // Append bytes + record contribution. Merge with the trailing log entry when it's
        // the same wire frame (out-of-order drains can trigger multiple on_data per process()).
        flow.bytes.insert(flow.bytes.end(),
                          reinterpret_cast<const std::uint8_t*>(data),
                          reinterpret_cast<const std::uint8_t*>(data) + len);
        if (!flow.wire_log.empty() &&
            flow.wire_log.back().first.timestamp_ns == current_wire.timestamp_ns) {
            flow.wire_log.back().second += len;
        } else {
            flow.wire_log.emplace_back(current_wire, len);
        }

        std::size_t pos = 0;
        std::size_t soupbin_packets_in_chunk = 0;
        while (pos + 3 <= flow.bytes.size()) {
            // SoupBin packet header: 2-byte big-endian length, 1-byte packet type, then payload.
            const std::uint16_t packet_length =
                static_cast<std::uint16_t>((std::uint16_t(flow.bytes[pos]) << 8) | flow.bytes[pos + 1]);
            if (packet_length == 0) { pos += 2; continue; }   // skip null sentinel
            const std::size_t span = static_cast<std::size_t>(2) + packet_length;
            if (pos + span > flow.bytes.size()) { break; } // need more bytes

            const std::uint8_t outer = flow.bytes[pos + 2];
            std::uint64_t id;
            if (is_data_bearing(outer) && packet_length >= 2) {
                const std::uint8_t inner = flow.bytes[pos + 3];
                id = (static_cast<std::uint64_t>(outer) << 8) | inner;
            } else {
                id = outer;
            }

            // Per-key sample: build a synthetic wire frame around the SoupBin packet's raw bytes
            // so the per-message pcap is self-contained — SoupBin packet at TCP-payload-offset 0,
            // replayable through any parser pipeline. Real wire frames here usually start mid-packet
            // (after preceding SoupBin packets) or carry only a fragment, which a from-scratch parser
            // can't make sense of.
            auto synth = synthesize_wire_frame(current_wire.timestamp_ns,
                                               flow.bytes.data() + pos, span);
            const auto it = smallest.find(id);
            if (it == smallest.end() || synth.bytes.size() < it->second.total_bytes) {
                smallest[id] = sample_of_one(std::move(synth));
            }

            // Reassembly example: when the SoupBin packet's bytes spanned more than one wire frame,
            // capture the original wire-frame sequence (preserves real TCP segmentation — useful
            // for testing reassembler behavior, not the message parser).
            if (reassembly_frames.empty()) {
                std::vector<Captured> contributors;
                std::size_t walked = 0;
                for (const auto& [frame, count] : flow.wire_log) {
                    if (walked >= pos + span) { break; }
                    if (walked + count > pos) { contributors.push_back(frame); }
                    walked += count;
                }
                if (contributors.size() > 1) { reassembly_frames = std::move(contributors); }
            }

            pos += span;
            soupbin_packets_in_chunk++;
        }

        // Drop consumed bytes from both buffer and contribution log in lock-step.
        if (pos > 0) {
            flow.bytes.erase(flow.bytes.begin(), flow.bytes.begin() + pos);
            std::size_t remaining = pos;
            while (remaining > 0 && !flow.wire_log.empty()) {
                auto& [frame, count] = flow.wire_log.front();
                if (count <= remaining) { remaining -= count; flow.wire_log.pop_front(); }
                else { count -= remaining; remaining = 0; }
            }
        }

        if (soupbin_packets_in_chunk > 1 && !multiple_messages) { multiple_messages = current_wire; }
    };

    while (pcap.advance()) {
        packet::Frame frame(pcap.data(), pcap.length());
        if (!frame.valid() || !frame.is_tcp()) { continue; }
        current_wire = capture_of(pcap);
        reassembler.process(frame);
    }

    write_samples(out_dir, smallest, multiple_messages, reassembly_frames);

    std::fprintf(stderr, "sampled %zu unique keys from %s -> %s\n",
                 smallest.size(), in_path.string().c_str(), out_dir.string().c_str());
    return 0;
}

} // namespace extractor
