// Iex.IexEquities.Deep.IexTp.v1.06 message tests over the packet corpus.
//
// Generated by CppGenerators — do not edit.

#include <cstdio>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/modern/iex/iexequities/deep/iextp/v1.06/definitions.hpp"

namespace protocol = ::iex::iexequities::deep::iextp::v1_06;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{value};
}

// Walk every frame in a capture and require the expected message to appear in it.
template <typename Message>
void expect(const char* name, const char* relative) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);

    std::size_t matched = 0;
    std::size_t messages = 0;
    std::size_t frames = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;

        protocol::MessageIterator iterator;
        iterator.initialize(frame.payload, frame.payload_len);

        while (iterator.next()) {
            ++messages;

            if (iterator.message_type == Message::message_type) { ++matched; }
        }
    }

    if (frames == 0) {
        std::printf("FAIL %s: no transport frames in capture\n", name);
        ++failures;
        return;
    }

    if (messages == 0) {
        std::printf("FAIL %s: no messages parsed from capture\n", name);
        ++failures;
        return;
    }

    if (matched == 0) {
        std::printf("FAIL %s: parsed %zu messages, none of the expected type\n", name, messages);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu of %zu messages\n", name, matched, messages);
}
}

int main() {
    std::printf("== Iex.IexEquities.Deep.IexTp.v1.06\n");

    expect<protocol::PriceLevelBuyUpdateMessage>("PriceLevelBuyUpdateMessage", "Iex/IexEquities.Deep.IexTp.v1.06/PriceLevelBuyUpdateMessage.pcap");
    expect<protocol::PriceLevelSellUpdateMessage>("PriceLevelSellUpdateMessage", "Iex/IexEquities.Deep.IexTp.v1.06/PriceLevelSellUpdateMessage.pcap");

    return failures == 0 ? 0 : 1;
}