// Generated by Scaled.Historical.Extractor.Cpp — branch table for Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 43ull: return "ClientPacket_DebugPacket";
        case 76ull: return "LoginRequestPacket";
        case 79ull: return "LogoutRequest";
        case 82ull: return "ClientHeartbeat";
        case 85ull: return "UnsequencedDataPacket";
        case 72057594037927979ull: return "ServerPacket_DebugPacket";
        case 72057594037928001ull: return "LoginAcceptedPacket";
        case 72057594037928008ull: return "ServerHeartbeat";
        case 72057594037928010ull: return "LoginRejectedPacket";
        case 72057594037928019ull: return "SequencedDataPacket";
        case 72057594037928026ull: return "EndOfSession";
        case 72057950520213569ull: return "ServerPacket_AddOrderNoMpidAttributionMessage";
        case 72057950520213570ull: return "ServerPacket_BrokenTradeMessage";
        case 72057950520213571ull: return "ServerPacket_OrderExecutedWithPriceMessage";
        case 72057950520213572ull: return "ServerPacket_OrderDeleteMessage";
        case 72057950520213573ull: return "ServerPacket_OrderExecutedMessage";
        case 72057950520213574ull: return "ServerPacket_AddOrderWithMpidAttributionMessage";
        case 72057950520213576ull: return "ServerPacket_StockTradingActionMessage";
        case 72057950520213577ull: return "ServerPacket_NetOrderImbalanceIndicatorMessage";
        case 72057950520213578ull: return "ServerPacket_LuldAuctionCollarMessage";
        case 72057950520213579ull: return "ServerPacket_IpoQuotingPeriodUpdate";
        case 72057950520213580ull: return "ServerPacket_MarketParticipantPositionMessage";
        case 72057950520213582ull: return "ServerPacket_RetailPriceImprovementIndicatorMessage";
        case 72057950520213583ull: return "ServerPacket_DirectListingWithCapitalRaisePriceDiscoveryMessage";
        case 72057950520213584ull: return "ServerPacket_NonCrossTradeMessage";
        case 72057950520213585ull: return "ServerPacket_CrossTradeMessage";
        case 72057950520213586ull: return "ServerPacket_StockDirectoryMessage";
        case 72057950520213587ull: return "ServerPacket_SystemEventMessage";
        case 72057950520213589ull: return "ServerPacket_OrderReplaceMessage";
        case 72057950520213590ull: return "ServerPacket_MwcbDeclineLevelMessage";
        case 72057950520213591ull: return "ServerPacket_MwcbStatusLevelMessage";
        case 72057950520213592ull: return "ServerPacket_OrderCancelMessage";
        case 72057950520213593ull: return "ServerPacket_RegShoShortSalePriceTestRestrictedIndicatorMessage";
        case 72057950520213608ull: return "ServerPacket_OperationalHaltMessage";
        case 144115188075855937ull: return "Packet_AddOrderNoMpidAttributionMessage";
        case 144115188075855938ull: return "Packet_BrokenTradeMessage";
        case 144115188075855939ull: return "Packet_OrderExecutedWithPriceMessage";
        case 144115188075855940ull: return "Packet_OrderDeleteMessage";
        case 144115188075855941ull: return "Packet_OrderExecutedMessage";
        case 144115188075855942ull: return "Packet_AddOrderWithMpidAttributionMessage";
        case 144115188075855944ull: return "Packet_StockTradingActionMessage";
        case 144115188075855945ull: return "Packet_NetOrderImbalanceIndicatorMessage";
        case 144115188075855946ull: return "Packet_LuldAuctionCollarMessage";
        case 144115188075855947ull: return "Packet_IpoQuotingPeriodUpdate";
        case 144115188075855948ull: return "Packet_MarketParticipantPositionMessage";
        case 144115188075855950ull: return "Packet_RetailPriceImprovementIndicatorMessage";
        case 144115188075855951ull: return "Packet_DirectListingWithCapitalRaisePriceDiscoveryMessage";
        case 144115188075855952ull: return "Packet_NonCrossTradeMessage";
        case 144115188075855953ull: return "Packet_CrossTradeMessage";
        case 144115188075855954ull: return "Packet_StockDirectoryMessage";
        case 144115188075855955ull: return "Packet_SystemEventMessage";
        case 144115188075855957ull: return "Packet_OrderReplaceMessage";
        case 144115188075855958ull: return "Packet_MwcbDeclineLevelMessage";
        case 144115188075855959ull: return "Packet_MwcbStatusLevelMessage";
        case 144115188075855960ull: return "Packet_OrderCancelMessage";
        case 144115188075855961ull: return "Packet_RegShoShortSalePriceTestRestrictedIndicatorMessage";
        case 144115188075855976ull: return "Packet_OperationalHaltMessage";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
