// Generated by Scaled.Historical.Extractor.Cpp — branch table for Nasdaq.NsmEquities.TotalView.Itch.v5.0.2023.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 65ull: return "AddOrderNoMpidAttributionMessage";
        case 66ull: return "BrokenTradeMessage";
        case 67ull: return "OrderExecutedWithPriceMessage";
        case 68ull: return "OrderDeleteMessage";
        case 69ull: return "OrderExecutedMessage";
        case 70ull: return "AddOrderWithMpidAttributionMessage";
        case 72ull: return "StockTradingActionMessage";
        case 73ull: return "NetOrderImbalanceIndicatorMessage";
        case 74ull: return "LuldAuctionCollarMessage";
        case 75ull: return "IpoQuotingPeriodUpdate";
        case 76ull: return "MarketParticipantPositionMessage";
        case 78ull: return "RetailPriceImprovementIndicatorMessage";
        case 79ull: return "DirectListingWithCapitalRaisePriceDiscoveryMessage";
        case 80ull: return "NonCrossTradeMessage";
        case 81ull: return "CrossTradeMessage";
        case 82ull: return "StockDirectoryMessage";
        case 83ull: return "SystemEventMessage";
        case 85ull: return "OrderReplaceMessage";
        case 86ull: return "MwcbDeclineLevelMessage";
        case 87ull: return "MwcbStatusLevelMessage";
        case 88ull: return "OrderCancelMessage";
        case 89ull: return "RegShoShortSalePriceTestRestrictedIndicatorMessage";
        case 104ull: return "OperationalHaltMessage";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
