// Generated by Scaled.Historical.Extractor.Cpp — branch table for Iex.IexEquities.Deep.IexTp.v1.06.
#pragma once

#include <cstdint>

namespace protocol::Branches {

// discriminator value -> short message name (PascalCase, suitable for filenames).
inline const char* name(std::uint64_t id) {
    switch (id) {
        case 5ull: return "PriceLevelSellUpdateMessage";
        case 8ull: return "PriceLevelBuyUpdateMessage";
        case 65ull: return "AuctionInformationMessage";
        case 66ull: return "TradeBreakMessage";
        case 68ull: return "SecurityDirectoryMessage";
        case 69ull: return "SecurityEventMessage";
        case 72ull: return "TradingStatusMessage";
        case 79ull: return "OperationalHaltStatusMessage";
        case 80ull: return "ShortSalePriceTestStatusMessage";
        case 83ull: return "SystemEventMessage";
        case 84ull: return "TradeReportMessage";
        case 88ull: return "OfficialPriceMessage";
        default: return nullptr;
    }
}

} // namespace protocol::Branches
